### ISSUE TITLE
jadx crash

### ISSUE THREAD

**Issue by LitterSun** [skylot/jadx#1139] opened 2021-03-31 03:27 UTC
jadx version: 1.2.0

2021-03-30 20:03:20.900 java[60506:5244594] +[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x129ae63e0
2021-03-30 20:03:20.901 java[60506:5244594] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x129ae63e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3791ab57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff707ab5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff37999b37 __CFExceptionProem + 0
	3   CoreFoundation                      0x00007fff3787f3bb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3787ed98 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007fff3789480f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff378947a3 ___CFXRegistrationPost1_block_invoke + 63
	7   CoreFoundation                      0x00007fff37894718 _CFXRegistrationPost1 + 372
	8   CoreFoundation                      0x00007fff37894384 ___CFXNotificationPost_block_invoke + 80
	9   CoreFoundation                      0x00007fff378644fd -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1554
	10  CoreFoundation                      0x00007fff378639a9 _CFXNotificationPost + 1351
	11  Foundation                          0x00007fff39ee1786 -[NSNotificationCenter postNotificationName:object:userInfo:] + 59
	12  AppKit                              0x00007fff34eed8ae __NSSelectedKeyboardInputSourcesChangedNotification + 58
	13  CoreFoundation                      0x00007fff3789480f __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	14  CoreFoundation                      0x00007fff378947a3 ___CFXRegistrationPost1_block_invoke + 63
	15  libdispatch.dylib                   0x00007fff718f96c4 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff718fa658 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff71905cab _dispatch_main_queue_callback_4CF + 936
	18  CoreFoundation                      0x00007fff378dde81 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	19  CoreFoundation                      0x00007fff3789dc87 __CFRunLoopRun + 2028
	20  CoreFoundation                      0x00007fff3789ce3e CFRunLoopRunSpecific + 462
	21  HIToolbox                           0x00007fff364c9abd RunCurrentEventLoopInMode + 292
	22  HIToolbox                           0x00007fff364c97d5 ReceiveNextEventCommon + 584
	23  HIToolbox                           0x00007fff364c9579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	24  AppKit                              0x00007fff34b0f039 _DPSNextEvent + 883
	25  AppKit                              0x00007fff34b0d880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	26  libosxapp.dylib                     0x000000010340291e -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	27  AppKit                              0x00007fff34aff58e -[NSApplication run] + 658
	28  libosxapp.dylib                     0x0000000103402763 +[NSApplicationAWT runAWTLoopWithApp:] + 222
	29  libawt_lwawt.dylib                  0x0000000129aac141 +[AWTStarter starter:headless:] + 834
	30  JavaNativeFoundation                0x00007fff3c1b9ff9 +[JNFRunLoop _performCopiedBlock:] + 15
	31  Foundation                          0x00007fff39f730dd __NSThreadPerformPerform + 204
	32  CoreFoundation                      0x00007fff3789ed52 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	33  CoreFoundation                      0x00007fff3789ecf1 __CFRunLoopDoSource0 + 103
	34  CoreFoundation                      0x00007fff3789eb0b __CFRunLoopDoSources0 + 209
	35  CoreFoundation                      0x00007fff3789d83a __CFRunLoopRun + 927
	36  CoreFoundation                      0x00007fff3789ce3e CFRunLoopRunSpecific + 462
	37  libjli.dylib                        0x0000000101a6e5f6 CreateExecutionEnvironment + 399
	38  libjli.dylib                        0x0000000101a6a787 JLI_Launch + 1315
	39  java                                0x0000000101a5ab6f main + 367
	40  libdyld.dylib                       0x00007fff71953cc9 start + 1
	41  ???                                 0x0000000000000009 0x0 + 9
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    60506 abort      ./jadx-1.2.0/bin/jadx-gui

**Comment by jpstotz** [comment] 2021-03-31 11:11
You seem to use Jadx on MacOS. What OS version do you use and what Java version?

Typically if a Java program crashes like this the problem is located in the used JRE not the application.

**Comment by LitterSun** [comment] 2021-03-31 11:14
> You seem to use Jadx on MacOS. What OS version do you use and what Java version?
> 
> Typically if a Java program crashes like this the problem is located in the used JRE not the application.

Yes, I'm currently using java 11. It's normal to switch to Java 1.8.

**Comment by skylot** [comment] 2021-03-31 13:44
I found this issue in JDK bug tracker: [JDK-8257242](https://bugs.openjdk.java.net/browse/JDK-8257242). It is marked as fixed, so you need to use the latest JDK version.

**Closed by skylot** 2021-03-31 13:44 UTC
Labels: Core, bug

**Comment by CreateChance** [comment] 2023-02-27 02:38
> I found this issue in JDK bug tracker: [JDK-8257242](https://bugs.openjdk.java.net/browse/JDK-8257242). It is marked as fixed, so you need to use the latest JDK version.

Still have the problem here, my JDK info:
```
java 11.0.10 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)
```
