### ISSUE TITLE
[feature] Don't consume CPU when idle

### ISSUE THREAD

**Issue by aj3423** [skylot/jadx#2030] opened 2023-10-09 21:00 UTC
### Describe your idea

It seems there is a background job running all the time, it consumes CPU. And the memory usage on the bottom bar changes all the time. 

I saw from other thread that it's indexing. But I have already opened files I need, just want to stay at that page and spend some time reading the source, no more indexing is necessary.

Is it possible to disable this background job with an option in preference?

Thanks.

**Comment by skylot** [comment] 2023-10-09 21:11
@aj3423 this is not normal behavior.
Jadx shouldn't run any long background tasks outside of loading, searching or manually enabled `Auto start background decompilation` option in preferences.
Does this issue appear only for one apk? If so, please share that apk.
Also, share jadx version and jdk version (from about window), and try [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Comment by aj3423** [comment] 2023-10-11 09:40
@skylot I can confirm the CPUs goes very high after global searching, and it goes down back if the window goes to background or even being resized. This happens with any apk, the attached is a helloworld apk generated by android studio, same problem. 
[app-debug.apk.zip](https://github.com/skylot/jadx/files/12867621/app-debug.apk.zip)

To reproduce:
1. open the apk in jadx-gui
2. global search with `ctrl + shift + f`, type "a", open any file 
3. the cpu goes high (4 or)
4. minimize or resize jadx, or just move mouse into the tab area that mark in red, then the cpu goes back down
![image](https://github.com/skylot/jadx/assets/4710875/7eecae55-3f96-4ccf-a81d-86965c10373c)


Don't know if it's os specific, I'm on  Fedora 38 XFCE.

**Comment by aj3423** [comment] 2023-10-22 00:51
I switched to KDE from XFCE, the problem still exists. Sometimes the cursor is changing all the time while high CPU.

https://github.com/skylot/jadx/assets/4710875/4db15e93-b0c8-4459-ab38-6f4adc733b43

**Comment by skylot** [comment] 2023-10-22 15:15
@aj3423 sorry, but I can't reproduce this issue :slightly_frowning_face:
It looks like a rendering problem, so using latest JRE may help.
Also, disabling bottom memory indicator (menu `View->Show memory usage bar`) may help.

Anyway, I will keep this issue open for some time, maybe someone else can reproduce and fix this issue.

**Comment by aj3423** [comment] 2023-10-22 22:39
@skylot Neither hiding memory bar nor changing java version works. But I tried changing the theme, seems the problem is gone as long as I use the default them, and if I choose any other theme, the CPU goes high again. 
![image](https://github.com/skylot/jadx/assets/4710875/695694b4-9cbc-4419-ba58-afe804fba68c)

**Comment by skylot** [comment] 2023-10-23 17:05
@aj3423 this means that FlatLaf causing this issue, or jadx uses it incorrect :slightly_frowning_face:
Just in case, please try [FlatLaf Demo](https://github.com/JFormDesigner/FlatLaf#demo), and check if it causes high CPU usage.

**Comment by aj3423** [comment] 2023-10-23 23:07
@skylot Seems the problem also exists in FlatLaf Demo, I fired [an issue](https://github.com/JFormDesigner/FlatLaf/issues/755) there and I'll feedback here later.

**Comment by DevCharly** [comment] 2023-11-05 18:59
I've analyzed the problem in FlatLaf Demo.
It is a bug in Java 17+ that occurs also in Metal L&F and under special conditions (right-to-left component orientation, text field, baseline layout). See https://github.com/JFormDesigner/FlatLaf/issues/755#issuecomment-1793810148 for details.

I'm not sure whether the problem in jadx is the same as in FlatLaf Demo.

@aj3423 could you capture some thread dumps of jadx (while CPU load is high)?
Java includes a command line tool called `jstack` that dumps stack of running Java app.
See: https://www.baeldung.com/java-thread-dump
It would be good to have several thread dumps (maybe 5 - 10) to find the cause of the CPU load.

**Comment by aj3423** [comment] 2023-11-06 04:24
@DevCharly Here are 10 logs captured with  `sleep 3 && jstack -l 92032 > 1.log`, during the 3 seconds, I activated the Jadx window to make sure it's consuming CPU, please check them out.
[10 logs.zip](https://github.com/skylot/jadx/files/13262396/10.logs.zip)

**Comment by DevCharly** [comment] 2023-11-07 17:45
All 10 logs show that jadx is repainting all the time...

In the meantime I was able to reproduce the issue (on Win11 and on Ubuntu).
It has something to do with **line wrapping**.
After enabling "Line Wrap" in editor context menu, CPU/GPU load goes up.

@aj3423 have you enabled line wrapping?
If yes, does CPU load go down if you disable line wrapping?

In the debugger I see that one of the tabbed panes is recalculating layout while repainting, which seems to cause a new repaint, which results in endless relayout and repaint...

Don't know the exact reason.

Since FlatLaf 3.2.2, this seems to be "fixed".
The commit d129be7e863353252f4ed78f6bc208544fbe7921 that @aj3423 uses, uses FlatLaf 3.2.1.

@aj3423 please use latest jadx commit.

**Comment by skylot** [comment] 2023-11-07 20:07
> It has something to do with line wrapping.

@DevCharly thanks! Indeed, with line wrapping enabled, I am also able to reproduce this issue. Although I also need to make jadx window inactive, and after I focus window again CPU load goes up.
I am using latest jadx commit which uses FlatLaf 3.2.5 (on Linux with Wayland, Java 17).

**Comment by aj3423** [comment] 2023-11-08 03:01
@DevCharly Indeed it's the LineWrap causing the CPU problem, after disabling it, the CPU never goes up again.  
But then I tried the latest Jadx, which uses FlatLaf 3.2.5, the problem still exists with LineWrap enabled. 
Here are 5 logs captured with latest Jadx https://github.com/skylot/jadx/commit/a989fa7e64bcd7c8a0ce39b8aeed83e1cc436665
[5 logs.zip](https://github.com/skylot/jadx/files/13291493/5.logs.zip)

**Comment by DevCharly** [comment] 2024-01-08 20:14
fixed with latest FlatLaf `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

Could you test that snapshot? Thanks.
Plan to release FlatLaf 3.3 in the next days...

**Comment by skylot** [comment] 2024-01-08 21:00
@DevCharly issue fixed for me  :tada: Thank you :+1:

**Comment by skylot** [comment] 2024-01-11 19:50
Fixed by updating FlatLaf to version 3.3.
To check, try [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Closed by skylot** 2024-01-11 19:50 UTC
Labels: bug, need help, GUI
