### ISSUE TITLE
[core] Use of template type instead of actual type

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#918] opened 2020-04-28 10:10 UTC
Hi, class `com.ebay.mobile.trend.TopicListingViewModel`
```java
    TopicListingViewModel(int i, @androidx.annotation.NonNull com.ebay.nautilus.domain.data.Trend.ListingSummary listingSummary, java.lang.String str) {
        this.viewType = i;
        this.trackingModule = str;
        this.trendItemImage = new com.ebay.nautilus.domain.data.image.ImageData(listingSummary.image.url);
        this.trendItemTitle = listingSummary.title;
        T t = listingSummary.displayPrice.value; // <<<<<
```

But if jump to `displayPrice` declaration, an actual type is defined
```java
    public static class ListingSummary implements android.os.Parcelable {
        //...
        public com.ebay.nautilus.domain.data.Trend.TextSpanValueProperty<com.ebay.nautilus.domain.data.BaseCommonType.Amount> displayPrice;
```
```java
    public static class TextSpanValueProperty<T> {
        public java.util.List<com.ebay.nautilus.domain.data.Trend.TextSpan> textSpans;
        public T value;
    }
```

so valid code should be
```java
    TopicListingViewModel(int i, @androidx.annotation.NonNull com.ebay.nautilus.domain.data.Trend.ListingSummary listingSummary, java.lang.String str) {
        this.viewType = i;
        this.trackingModule = str;
        this.trendItemImage = new com.ebay.nautilus.domain.data.image.ImageData(listingSummary.image.url);
        this.trendItemTitle = listingSummary.title;
        com.ebay.nautilus.domain.data.BaseCommonType.Amount t = listingSummary.displayPrice.value; // <<<<<
```
because type `T` is unknown at this step

APK: https://drive.google.com/file/d/1ICfL4A22K-KhVkw5RwvWdLJA8111iYvG/view?usp=sharing

**Comment by sergey-wowwow** [comment] 2020-08-10 11:08
@skylot 
I've provided an incorrect link to a different app. Do you know the affected app or I should close this issue?

**Comment by skylot** [comment] 2020-08-10 19:50
@sergey-wowwow look like here should be link to `com.ebay.mobile_2020-01-30.apk` ([this link](https://drive.google.com/file/d/1qC3tlWs9AtPBpyS6iU9kcSphLryfJOxi/view?usp=sharing)).
Using this apk I successfully reproduce the issue.

**Comment by bagipro** [comment] 2021-05-29 19:44
Hey @skylot,
Can you please look at this issue? This error happens pretty often in models

Thanks!

**Comment by skylot** [comment] 2021-05-29 20:07
> Can you please look at this issue?

Sure, I make a simple test case and will definitely fix it this time :+1:

**Comment by skylot** [comment] 2021-05-30 09:45
@bagipro I made a fix.
But looks like this case is too narrow (only for instance fields), so similar issues can still occur.

**Closed by skylot** 2021-05-30 09:45 UTC
Labels: Core, bug

**Comment by bagipro** [comment] 2021-05-31 13:35
Thanks!
