### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by LaryGala3** [skylot/jadx#1468] opened 2022-04-26 07:22 UTC
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.3.4
* Java version: 1.8.0_241
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 7193 MB
* Program args: 

```
java.lang.NullPointerException
	at jadx.gui.ui.dialog.UsageDialog.lambda$getMethodUseIn$1(UsageDialog.java:78)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at jadx.gui.ui.dialog.UsageDialog.getMethodUseIn(UsageDialog.java:78)
	at jadx.gui.ui.dialog.UsageDialog.collectUsageData(UsageDialog.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by jpstotz** [comment] 2022-04-26 07:26
Possible duplicate of #1425 please update to the latest Jadx version 1.3.5.

**Comment by LaryGala3** [comment] 2022-04-26 07:38
> Possible duplicate of #1425 please update to the latest Jadx version 1.3.5.

I will do it now.
Thanks!!!

**Closed** 2022-04-29 12:16 UTC
Labels: no-reply
