### ISSUE TITLE
[feature] jadx GUI - Allow moving classes among packages

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1900] opened 2023-06-08 12:07 UTC
*Describe your idea:*

Jadx GUI allows only renaming classes (e.g., when clicking Class name -> Rename - Entering a value), but there's no way to move it to a different package.

Would it be possible to add two fields for class name rename:
1. Package name
2. Class name

**Comment by skylot** [comment] 2023-06-08 13:48
Using unstable build (i.e. master branch) you can enter in rename dialog full class name, so the class will be moved to that package.
But this feature not very stable right now, so it can cause some issues like not updated packages tree or similar, as workaround reloading project should help (with reload toolbar button or F5 key).
After I fix these issues, I will add a describing hint to rename dialog.

I will close this issue as a duplicate of #1590

**Closed by skylot** 2023-06-08 13:48 UTC
Labels: new feature
