### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null

### ISSUE THREAD

**Issue by changjinzhuan** [skylot/jadx#1979] opened 2023-08-01 07:59 UTC
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.7
* Java version: 19.0.2
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 6464 MB

```
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null
	at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by jpstotz** [comment] 2023-08-01 08:07
Duplicate of #1657

**Closed by jpstotz** 2023-08-01 08:07 UTC
