### ISSUE TITLE
Latest unstable build not updated

### ISSUE THREAD

**Issue by redmi111** [skylot/jadx#1113] opened 2021-02-04 06:20 UTC
The latest Unstable files are not updated on bintray.com. The last update happened on Jan 24, 2021

**Comment by skylot** [comment] 2021-02-04 11:34
Due to new pricing model on [Travis CI](travis-ci.com), check [this post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), jadx used its free credits so no  more builds here. To fix this I already migrate simple test build to GitHub Actions, so new commits and PRs verification works now.

About Bintray: looks like it closing, check [this post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). 
> February 28th | No more submissions will be accepted to Bintray, JCenter

So I will not migrate this part from Travis to GitHub Actions, I just need to find a new place for storing unstable binaries :cry:

**Comment by Surendrajat** [comment] 2021-02-05 07:22
@skylot how about pushing it to GitHub Actions' [artifact section](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts)? It stores artifacts for 90 days which I think is sufficient for unstable builds. I can open a PR for that if you like.
![Screenshot from 2021-01-04 21-18-43](https://user-images.githubusercontent.com/11215000/107002217-e4796c80-67b0-11eb-9041-c73ee8416268.png)

**Comment by skylot** [comment] 2021-02-05 17:24
@Surendrajat thanks for help! I know about artifacts in GitHub Actions and I will use it. Right now I am learning how to adjust workflows to my needs, so I will try to finish it myself.

**Comment by skylot** [comment] 2021-02-05 21:55
I managed to make it work, check [this](https://github.com/skylot/jadx/actions/runs/541674862) build.
But I found some issues:
1. Due to packing all artifacts in one zip file, it is not possible now to have separate artifacts (like `.zip` and `.exe` previously). Check [limitations](https://github.com/actions/upload-artifact#zipped-artifact-downloads) and issue  https://github.com/actions/upload-artifact/issues/39. So for now only `.zip` artifact is available for download.
2. I don't find a way to have a link to just **latest build** to simplify navigation.

**Comment by Surendrajat** [comment] 2021-02-06 01:42
@skylot 
1. Until the issue is resolved, you can repeat the same upload step for .exe file and name it something like `jadx*.exe` to differentiate. So users will be aware and can extract real .exe file from .zip file.
2. Yeah, there isn't a way for that(https://github.com/actions/upload-artifact/issues/52) and also artifacts are only available if you are logged in to GitHub(https://github.com/actions/upload-artifact/issues/51). However, you can check https://nightly.link out for this purpose. It works very well if your artifact has a fixed name like `jadx-dev.zip`.

**Comment by skylot** [comment] 2021-02-06 12:57
@Surendrajat thank you for great suggestions! Now it looks much better!
I add link to [unstable build](https://nightly.link/skylot/jadx/workflows/build/master) to README, and I think we can close this issue now.

**Closed by skylot** 2021-02-06 12:57 UTC
Labels: question
