### ISSUE TITLE
[core] Duplicated region in loop

### ISSUE THREAD

**Issue by yawkat** [skylot/jadx#1040] opened 2020-12-01 11:59 UTC
Test case:

```smali
.class public Ltrycatch/TestA;
.super Landroid/support/graphics/drawable/VectorDrawableCommon;
.source "SourceFile"

.method public static create()V
    .registers 6

    :try_start

    :loop

    const/4 v1, 0x0

    const/4 v2, 0x1

    if-eq v1, v2, :cond

    const/4 v3, 0x2

    if-eq v1, v3, :cond

    goto :loop

    :cond
    if-eq v1, v2, :end

    return-void

    :try_end
    .catch Ljava/io/IOException; {:try_start .. :try_end} :end

    :end
    return-void
.end method
```

```java
package jadx.tests.integration.trycatch;

import jadx.core.dex.nodes.ClassNode;
import jadx.tests.api.SmaliTest;
import org.junit.jupiter.api.Test;

public class TestA extends SmaliTest {
	@Test
	public void test() {
		outputCFG();
		ClassNode cls = getClassNodeFromSmaliWithPkg("trycatch", "TestA");
		String code = cls.getCode().toString();
	}
}
```

Error:

```
12:14:52 DEBUG - Loaded plugin: SmaliInput
12:14:52 DEBUG - Loaded plugin: JavaConvert
12:14:52 DEBUG - Loaded plugin: DexInput
12:14:52 DEBUG - Effective jadx args: JadxArgs{inputFiles=[src/test/smali/trycatch/TestA.smali], outDir=test-out-tmp, outDirSrc=test-out-tmp/sources, outDirRes=test-out-tmp/resources, threadsCount=1, cfgOutput=true, rawCFGOutput=true, fallbackMode=false, showInconsistentCode=true, useImports=true, skipResources=true, skipSources=false, deobfuscationOn=false, deobfuscationForceSave=false, useSourceNameAsClassAlias=false, parseKotlinMetadata=false, deobfuscationMinLength=0, deobfuscationMaxLength=2147483647, escapeUnicode=false, replaceConsts=true, respectBytecodeAccModifiers=false, exportAsGradleProject=false, fsCaseSensitive=false, renameFlags=[CASE, VALID, PRINTABLE], outputFormat=JAVA, codeCache=InMemoryCodeCache}
12:14:52 INFO  - loading ...
12:14:52 DEBUG - Loading dex: /tmp/jadx-12846887616930292442.dex
12:14:52 DEBUG - Classes loaded: 1
12:14:52 DEBUG - Clst file loaded in 70ms, classes: 4750, methods: 11879
12:14:52 DEBUG - '.arsc' file not found
12:14:52 DEBUG - Dependency collection done in 14ms
12:14:52 WARN  - Removed duplicated region for block: B:2:0x0004  in method: trycatch.TestA.create():void, file: /tmp/jadx-12846887616930292442.dex
12:14:52 DEBUG - Duplicated block: trycatch.TestA.create():void - B:1:0x0002
12:14:52 DEBUG - Duplicated block: trycatch.TestA.create():void - B:1:0x0002
-----------------------------------------------------------
package trycatch;

import android.support.graphics.drawable.VectorDrawableCommon;

public class TestA extends VectorDrawableCommon {
    /* JADX WARNING: Removed duplicated region for block: B:2:0x0004  */
    public static void create() {
        while (0 != 1 && 0 != 2) {
            while (0 != 1) {
                while (0 != 1) {
                }
            }
        }
        if (0 == 1) {
        }
    }
}
-----------------------------------------------------------

Method with problems: trycatch.TestA.create():void
 INLINE_NOT_NEEDED
 Removed duplicated region for block: B:2:0x0004 
org.opentest4j.AssertionFailedError: Method with problems: trycatch.TestA.create():void
 INLINE_NOT_NEEDED
 Removed duplicated region for block: B:2:0x0004 
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:117)
	at jadx.tests.api.IntegrationTest.checkCode(IntegrationTest.java:255)
	at java.base/java.util.Collections$SingletonList.forEach(Collections.java:4933)
	at jadx.tests.api.IntegrationTest.decompileAndCheck(IntegrationTest.java:210)
	at jadx.tests.api.IntegrationTest.getClassNodeFromFiles(IntegrationTest.java:160)
	at jadx.tests.api.SmaliTest.getClassNodeFromSmali(SmaliTest.java:26)
	at jadx.tests.api.SmaliTest.getClassNodeFromSmaliWithPkg(SmaliTest.java:45)
	at jadx.tests.integration.trycatch.TestA.test(TestA.java:124)

jadx.tests.integration.trycatch.TestA > test() FAILED
    org.opentest4j.AssertionFailedError at TestA.java:124
```

(for reference: control flow graph https://s.yawk.at/S26GBvxX )

I can kind of follow along what happens here:

1. The loop at block 0 begins processing (`processLoop`).
2. The loop header (block 2) is merged with the if in block 3. The `thenBlock` of the merged `condInfo` is block 4, the else block is 0. Block 3 is marked as ADDED_TO_REGION.
3. The loop body begins traversal.
4. Block 3 is hit. It is ADDED_TO_REGION from step 2, so `processIf` just returns its `then` branch (block 0). In reality, the if is part of the merged if, and should have block 4 as the `then` branch.

The solution I can think of is adding a property to all if blocks that are part of a merged if, containing the merged `IfInfo`. However looking at the code this isn't straight-forward (maybe through an attribute?) and I don't know if it's a good idea at all – `IfInfo` is so far used mostly as a helper class locally and I don't know if saving it long-term as an attribute would have other implications.

**Comment by skylot** [comment] 2020-12-01 13:35
@yawkat the main problem here that the loop body is empty and instead of omitting it jadx starts to traverse same loop again. I made a simple fix in branch `issue-1040`, so now the output code is correct. But your test case is so reduced that correct code is not compilable (unreachable `if`), I prefer to use compilable code to allow the compiler to make most work of checking code.
Anyway, please check my solution and how it works on original test case, because I am not sure about current check (loop start) maybe here must be something more complicated.

**Comment by yawkat** [comment] 2020-12-01 13:54
I'm a bit reluctant to share the original source publicly because of copyright reasons. However, this patch should make the code compile:

```patch
--- <unnamed>
+++ <unnamed>
@@ -1,6 +1,8 @@
 .class public Ltrycatch/TestA;
-.super Landroid/support/graphics/drawable/VectorDrawableCommon;
+.super Ljava/lang/Object;
 .source "SourceFile"
+
+.field private static test:I
 
 .method public static create()V
     .registers 6
@@ -9,7 +11,7 @@
 
     :loop
 
-    const/4 v1, 0x0
+    sget v1, Ltrycatch/TestA;->test:I
 
     const/4 v2, 0x1
 

```

It looks like your change indeed fixed the issue in my original test case, but it persists in this updated version. 

It's a bit annoying that I can't share the original I guess, since there could be even further issues preventing decompilation of that, but I hope this is enough.

**Comment by skylot** [comment] 2020-12-03 18:53
@yawkat updated test case cover different code in jadx, so fix is also different.
This time main issue is duplicated code outside of the loop (copied into loop). I made fix to check if traversed block listed as exit, in this case we must stop processing and if it is inside loop optionally add `break` or `continue` instructions.
Please check this change against original test case, and I hope it will not affect other cases.

**Comment by yawkat** [comment] 2020-12-03 19:20
Yes, that solves the issue! Thanks.

**Comment by skylot** [comment] 2020-12-03 19:32
Great!
I pushed fixes into master.

**Closed by skylot** 2020-12-03 19:32 UTC
Labels: Core, bug

**Comment by alissonlauffer** [comment] 2020-12-03 19:34
@skylot I've built jadx with the `issue-1040` branch and noticed some regressions regarding to missing code blocks (They are not reproducible with master):

In class a.a.a.g.a:

<details><summary>Show diffs</summary>
<p>

```diff java
+    /* JADX WARNING: Code restructure failed: missing block: B:25:0x0057, code lost:
+        r5 = false;
+     */
     public static String a(String str, String str2) {
         if (str2 == null || str2.isEmpty()) {
             return str;
@@ -55,10 +58,9 @@ public class a {
                     int i4 = indexOf2 - 1;
                     int length2 = substring.length() + indexOf2;
                     if ((i4 < 0 || str.charAt(i4) == ',') && (length2 >= str.length() || str.charAt(length2) == ',')) {
-                        z = false;
-                    } else {
-                        i3 = indexOf2 + 1;
+                        break;
                     }
+                    i3 = indexOf2 + 1;
                 }
                 if (z) {
                     str = str + "," + substring;
```

and

```diff
+    /* JADX WARNING: Code restructure failed: missing block: B:25:0x0056, code lost:
+        if (r5 != 0) goto L_0x006d;
+     */
+    /* JADX WARNING: Code restructure failed: missing block: B:27:0x005c, code lost:
+        if (r7 < r9.length()) goto L_0x0061;
+     */
+    /* JADX WARNING: Code restructure failed: missing block: B:28:0x005e, code lost:
+        r9 = "";
+     */
+    /* JADX WARNING: Code restructure failed: missing block: B:29:0x0061, code lost:
+        r9 = r9.substring((r5 + r2.length()) + 1);
+     */
+    /* JADX WARNING: Code restructure failed: missing block: B:30:0x006d, code lost:
+        r9 = r9.substring(0, r6) + r9.substring(r5 + r2.length());
+     */
     public static String u(String str, String str2) {
         if (str != null && !str.isEmpty() && str2 != null && !str2.isEmpty()) {
             int length = str2.length();
@@ -597,13 +615,10 @@ public class a {
                         }
                         int i4 = indexOf2 - 1;
                         int length2 = substring.length() + indexOf2;
-                        if ((i4 >= 0 && str.charAt(i4) != ',') || (length2 < str.length() && str.charAt(length2) != ',')) {
-                            i3 = indexOf2 + 1;
-                        } else if (indexOf2 == 0) {
-                            str = length2 >= str.length() ? "" : str.substring(indexOf2 + substring.length() + 1);
-                        } else {
-                            str = str.substring(0, i4) + str.substring(indexOf2 + substring.length());
+                        if ((i4 < 0 || str.charAt(i4) == ',') && (length2 >= str.length() || str.charAt(length2) == ',')) {
+                            break;
                         }
+                        i3 = indexOf2 + 1;
                     }
                 }
```

</p>
</details>

APK: https://apkpure.com/via-browser-fast-light-geek-best-choice/mark.via.gp/download/20201129-APK
