### ISSUE TITLE
Non-deterministic results

### ISSUE THREAD

**Issue by razaina** [skylot/jadx#157] opened 2017-01-26 10:41 UTC
Hi

For some reason, jadx's results are not always the same. Why?

#!/usr/bin/env python
import subprocess
import sys
subprocess.run(('jadx -j 1 -d out%s --show-bad-code --escape-unicode -v myapp.dex' % sys.argv[1]).split())

-----

for i in 10 11 12 13 14 15; do
    mkdir -p out$i
    time ./runjadx.py $i >| $i.txt
done

-----

./runjadx.py $i >| $i.txt  283.19s user 2.85s system 387% cpu 1:13.79 total
./runjadx.py $i >| $i.txt  249.48s user 2.65s system 354% cpu 1:11.12 total
./runjadx.py $i >| $i.txt  238.89s user 2.80s system 345% cpu 1:09.86 total
./runjadx.py $i >| $i.txt  239.49s user 2.45s system 341% cpu 1:10.89 total
./runjadx.py $i >| $i.txt  240.80s user 2.55s system 343% cpu 1:10.76 total
./runjadx.py $i >| $i.txt  249.95s user 2.78s system 353% cpu 1:11.59 total

-----

% du -s out1
41752   out10
41828   out11
41828   out12
41668   out13
41668   out14
41588   out15

**Comment by skylot** [comment] 2017-01-26 10:47
Can you make a diff between some pair of folders, what exactly is different

**Comment by razaina** [comment] 2017-01-26 12:26
Hi  

ok I made a diff:

if you look at the 2 first images I attached, one can notice that there are some slight differences regarding variables renaming or their declarations. I don't think that it is a big issue.

However there are some cases that create a lot of differences. An example is the 3rd image where sometimes jadx just fails in decompiling a given function. This obviously creates differences in the size of the resulting file which is ok, but why after 6 successive runs, raised exceptions are not always the same.


[1] ![1](https://cloud.githubusercontent.com/assets/360746/22331043/88a15022-e3c9-11e6-813d-69127095b842.png)


[2] ![2](https://cloud.githubusercontent.com/assets/360746/22331044/88a32398-e3c9-11e6-94bc-70b7d7354ee9.png)


[3] ![3](https://cloud.githubusercontent.com/assets/360746/22331228/a24fe604-e3ca-11e6-8163-94b0a60e2577.png)

**Comment by skylot** [comment] 2017-01-26 12:44
Thank you !!!
It is very interesting research about sometimes raised exceptions.
About variable names I think I know how to fix it.

**Comment by razaina** [comment] 2017-01-26 14:31
You're welcome.

can I send you another screenshot in private?

**Comment by sergey-wowwow** [comment] 2019-04-21 08:55
@razaina 
Please recheck the issue now. I remember a few commits related to making jadx more deterministic.

**Comment by dobrakmato** [comment] 2019-06-05 16:37
Is there any progress on this issue? It seems the JADX (even the nightly build) is still not deterministic and gives different results on each run.

**Comment by jpstotz** [comment] 2019-06-06 11:27
@dobrakmato Then please provide some code samples including the used apk file. The original examples are more than two years old. Jadx has evolved a lot during that time.

**Comment by dobrakmato** [comment] 2019-06-06 15:48
I run JADX with following arguments: `--no-debug-info -dr directory -ds directory app.apk`

The APK i run it with is: https://apkcombo.com/en-sk/apk-downloader/?q=sk.zltymelon

The difference is in extracted resources and/or in random files. Each time I run the jaxd different files are decompiled / extracted differently.

![image](https://user-images.githubusercontent.com/779469/59031795-f5980a80-8864-11e9-84d3-745177c7511f.png)

![image](https://user-images.githubusercontent.com/779469/59031883-3859e280-8865-11e9-8851-8009b012aa37.png)

![image](https://user-images.githubusercontent.com/779469/59031958-6b03db00-8865-11e9-8ada-8f0082739fc8.png)

![image](https://user-images.githubusercontent.com/779469/59032120-c9c95480-8865-11e9-846d-a85f7aa65508.png)

![image](https://user-images.githubusercontent.com/779469/59043586-c8efed00-887c-11e9-8d34-5c8607cd81a3.png)

**Comment by jpstotz** [comment] 2019-06-06 17:26
OK, in 1. & 2. and 3 are namespaces (present/missing) in XML resources - strange but not really critical.

In 3. We have a different stack trace of a not decompilable class. This is caused by the multi-threaded decompilation. The order of the classes that are decompiled is not deterministic because of the multi-threaded decompilation. Therefore I would consider 3. that as a totally irrelevant.

In 4. we the stacktrace again and the second part of 4. seems to be multiple xml namespaces that are ordered differently. Looks like the namespaces are collected in a `HashMap` which does not has a specific order. May be we can sort the namespaces alphabetically before printing them.

In 5. we have two methods that are exchanged. On the text comparison level this is a difference, however on Java source code level both versions are equal. Therefore I would call this not a problem but an an inconvenience.

**Comment by sergey-wowwow** [comment] 2020-05-29 17:36
Seems to be fixed now

**Closed by sergey-wowwow** 2020-05-29 17:36 UTC
