### ISSUE TITLE
JadX decompiler via .bat on app built from Android Studio 3.1.2 - ERROR - NullPointerException in pass: RegionMakerVisitor in method: android.arch.lifecycle.Lifecycling

### ISSUE THREAD

**Issue by bensh** [skylot/jadx#279] opened 2018-05-17 15:33 UTC
[jadxbug.txt](https://github.com/skylot/jadx/files/2013832/jadxbug.txt)
attached output of errors.
happy to provide the .apk if required.

ERROR -   Method: android.support.v7.widget.SuggestionsAdapter.getDrawableFromResourceUri(android.net.Uri):android.graphics.drawable.Drawable
ERROR -   Method: android.support.v7.widget.SuggestionsAdapter.getDrawableFromResourceValue(java.lang.String):android.graphics.drawable.Drawable
ERROR -   Method: android.support.v7.widget.SwitchCompat.animateThumbToCheckedState(boolean):void
ERROR -   Method: android.support.v7.widget.SwitchCompat.stopDrag(android.view.MotionEvent):void
ERROR -   Method: android.support.v7.widget.ToolbarWidgetWrapper.<init>(android.support.v7.widget.Toolbar, boolean, int, int):void
ERROR -   Method: android.support.v7.widget.ViewUtils.<clinit>():void
ERROR -   Method: android.support.v7.widget.ViewUtils.makeOptionalFitsSystemWindows(android.view.View):void
ERROR -   Method: com.bensh.loginbypass.Registration.regBtn(android.view.View):void
ERROR - finished with errors

**Comment by sergey-wowwow** [comment] 2018-05-17 15:43
@bensh this issue was reported dozens of times like here https://github.com/skylot/jadx/issues/250

@skylot isn't is possible when ``` --show-bad-code ``` option is supplied output sources without try/catches? It could work for the most of methods

**Comment by skylot** [comment] 2018-05-17 20:53
@sergey-wowwow `--show-bad-code` allows to view not fully restructured or incomplete code (like missing or duplicated instructions). Such errors not always caused by broken try/catch processing, but it can be helpful to restart method decompilation without try/catch processing. I already made similar restart for failed finally block extraction. So I think I can do what you ask.

@bensh I will close this issue as a duplicate of #250, other issues in your log also known, but I don't have enough time to fix them. Sorry :(

**Closed by skylot** 2018-05-17 20:53 UTC
