### ISSUE TITLE
Manual rename class

### ISSUE THREAD

**Issue by Sputuks3** [skylot/jadx#88] opened 2015-09-21 07:05 UTC
I need to be able to manually rename classes and packages and have changes reflected throughout code

**Comment by killolol** [comment] 2015-09-23 16:30
Yes, refactoring will be really cool feature.

**Comment by h3ku** [comment] 2016-05-31 17:37
Yep, I think refactoring of methods, classes, variables... can be really good.

**Comment by glzlaohuai** [comment] 2018-02-27 03:36
Have the same need...

**Comment by jpstotz** [comment] 2018-02-27 07:26
There is currently no UI option for doing so. However you can rename classes manually:

If the deobfuscation has been activated a ".jobf" file is created next to the opened APK file. The file contains the class name mappings and can be edited using any text editor. 
You can rename the classes there and then reload the APK file.

**Comment by mingyuan-xia** [comment] 2018-05-30 10:16
This looks more like a generic code editor functionality.
Though the use case is a demanding one, I would suggest offloading that to a more professional coding environment like IntelliJ.
IDEs offer way better code editing, highlighting, refactoring, searching, suggestion, and error correction capability and we should get the best of both instead of spending quite a lot efforts re-implementing a naive one in Jadx.

**Comment by nic-hartley** [comment] 2019-03-14 14:16
I think JADX would have an advantage over normal IDEs in this case, though -- it's the one assigning names (e.g. `str4`) to the variables used, and it _has_ to know exactly where all those names are, because... it puts them there. There'd be no heuristics to determine if one name is really another name, no missed edge cases, nothing. It's by no means trivial, but it's not as hard as writing a "real" source code refactoring engine, because you're _not using the source code_.

**Comment by idb-** [comment] 2019-03-15 02:47
Maybe actual code refactoring isn't necessary, but just adding an alias to a method/class/field/whatever that is searchable like anything else would be would help a lot, especially if those comments could be displayed in the cross references list.

**Comment by Te-k** [comment] 2019-09-05 12:29
I totally agree that this feature would be really helpful for reversers (also renaming functions and variables). I don't think it is a code editor function, more an alias on what is actually in the APK to be able to understand the code better, than a real change of what the code is. Ideally, it would be nice to keep this aliases in a separated file than the apk, so that the APK is unchanged (a file that could also contain comments as in #359 )

**Comment by sergey-wowwow** [comment] 2020-04-28 18:43
Looks like it was implemented, so it's time to close this ticket

**Closed by sergey-wowwow** 2020-04-28 18:43 UTC
Labels: GUI

**Comment by mFIND** [comment] 2020-08-11 13:47
Hi,
Today I cloned and build the repo, eager to use new renaming functionality to good use :)
Sadly I have two problems on my machine (Linux; Ubuntu 18.04 LTS).
First: "Cancel" button is not visible before hovering my mouse over it.
Second: New window shown on the screenshot below is not editable - I found no easy way for changing displayed text. After clicking "Rename", the window disappears, leaving me without ability to modify method name (and probably anything else, like class names?) from GUI.
![image](https://user-images.githubusercontent.com/6615448/89904122-d6270b00-dbe8-11ea-9241-b681eef954cf.png)
If I did not mention some crucial information about my environment, please let me know :)

**Comment by skylot** [comment] 2020-08-11 15:07
@mFIND can you try to resize a window of rename dialog? As I remember a similar issue was already reported.
Also, I plan to move rename dialog to the editor bar similar to search bar (as mentioned in https://github.com/skylot/jadx/issues/791#issuecomment-575778870)

**Comment by mFIND** [comment] 2020-08-12 06:47
@skylot Thank you for prompt reply :)
Indeed the dialog was resizeable, haven't noticed!
I couldn't find similar issue you mentioned (maybe it's closed?), but regarding comment https://github.com/skylot/jadx/issues/791#issuecomment-575778870, I have found one(two?) more regression(s) when using renaming feature.
1. I have created a 'project' (.jadx file), but after opening it and renaming one method, and waiting for refresh to finish, I have noticed, that I was unable to rename more things before reopening the project.
2. At the same time, (Global) Text search was broken, it wouldn't show any results when searching for changed or unchanged method.
After reopening the project the issue(s) were resolved, and I could rename more than one method/class/etc in succession.
Two important things to note:
1. This bug might be unstable, I tried one more time and didn't succeed, I don't know how rare this one is.
2. When I tried renaming and it didn't work... well.. it worked partially. I couldn't see any change until reopening the project - after that changes were visible/searchable
