### ISSUE TITLE
[core] Compilation issue due to variable inlining

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#1338] opened 2022-01-14 23:26 UTC
This example produces a compilation issue after decompiling.

```java
import java.util.HashMap;
import java.util.Map;

public class JadxTest {
  public String test() {
    Map<String, String> map = new HashMap<>();
    return map.get("test");
  }
}
```

This is the decompilation result (tested with openjdk 8, latest git, java-input and java-convert)

```java
import java.util.HashMap;

public class JadxTest {
    public String test() {
        return new HashMap<>().get("test");
    }
}
```

In my opinion named variables (visible in smali) should not be inlined. Their names might help to understand the context.

This example can be used for unit tests.

**Comment by skylot** [comment] 2022-01-28 19:16
@nitram84 I commit a change to reject inline of named variables, so this issue is resolved.
But I don't check for missing generics (i.e. `new HashMap<>()`), because it is only possible if type with generics applied for variable, but name got rejected. Not sure if this needed, so maybe I will fix this later.
Also, during fix I encounter many small issues in different parts of jadx and these changes can cause new regressions, hope not so many :sweat_smile:

**Comment by nitram84** [comment] 2022-02-13 14:27
@skylot Thank you for fixing this issues! I haven't seen regressions due this fix so far. I think this issue can be closed. For possible regressions or issues with generics I think the best way is to open a new issue if there is a failing case.

**Comment by skylot** [comment] 2022-02-13 14:38
> For possible regressions or issues with generics I think the best way is to open a new issue if there is a failing case

@nitram84 sure, closing

**Closed by skylot** 2022-02-13 14:38 UTC
Labels: bug, Core
