### ISSUE TITLE
java.lang.IllegalArgumentException: newPosition > limit: (67079825 > 8454316)

### ISSUE THREAD

**Issue by janecms** [skylot/jadx#1653] opened 2022-08-23 10:29 UTC
version 1.4.4

The Error info
        /* JADX WARN: Failed to parse debug info
        java.lang.IllegalArgumentException: newPosition > limit: (67079825 > 8454316)
        	at java.base/java.nio.Buffer.createPositionException(Unknown Source)
        	at java.base/java.nio.Buffer.position(Unknown Source)
        	at java.base/java.nio.ByteBuffer.position(Unknown Source)
        	at jadx.plugins.input.dex.sections.SectionReader.absPos(SectionReader.java:82)
        	at jadx.plugins.input.dex.sections.debuginfo.DebugInfoParser.process(DebugInfoParser.java:84)
        	at jadx.plugins.input.dex.sections.DexCodeReader.getDebugInfo(DexCodeReader.java:118)
        	at jadx.core.dex.nodes.MethodNode.getDebugInfo(MethodNode.java:564)
        	at jadx.core.dex.visitors.debuginfo.DebugInfoAttachVisitor.visit(DebugInfoAttachVisitor.java:39)
         */

Now, I think  how to resole this question.
Thanks

**Comment by skylot** [comment] 2022-09-01 14:59
> Now, I think how to resole this question.

@janecms do you want to prepare a PR for that issue? PR is always welcome :slightly_smiling_face:
Anyway, it will be nice to provide a sample, so we can reproduce/check this issue.

**Comment by sulab999** [comment] 2022-11-24 02:40
how to resole??

**Comment by jpstotz** [comment] 2022-11-24 08:15
@sulab999 @janecms The best way to resolve an issue that is caused by a certain DEX/APK files is providing the APK file. 

@janecms In your original post you wrote ` Now, I think how to resole this question.` Most people would interpret this sentence this way "I think now I know what changes needed to be done in Jadx to resolve this issue in Jadx". Thus skyot proposed to you to open a PR. If this sentence was meant in a different way please tell it to us.

**Comment by sulab999** [comment] 2022-12-01 02:38
this apk
https://www.amazon.com/clouddrive/share/jADAfCDcUu9dEnrxSUwe0MS3aCCVg7CBGWvthsD90mk

**Comment by ya121y** [comment] 2024-03-01 20:17
Hey there! any updates about this?

**Comment by skylot** [comment] 2024-03-02 18:20
@ya121y we still do not have sample to reproduce this issue.
Sample provided by @sulab999 not having this exact issue (checked with latest unstable build).

@ya121y if you can share a sample please open a new issue, I will close this one because it is old and useless now.

**Comment by draekko** [comment] 2024-09-11 10:22
I know this was closed for lack of info but am getting it with the coospo CoospoRide app (current app  com.onecoder.coosporide v2.5.31 does as well as prior versions). Was trying to figure out how it talks to my ble hardware but nothing gets decoded. App can be had off the Play store or from apkpure https://apkpure.com/coosporide/com.onecoder.coosporide

One example error message from one of the fragment classes, but this seems to happen with pretty much all the classes.

`/* JADX WARN: Failed to parse debug info
    java.lang.IllegalArgumentException: newPosition > limit: (67042708 > 8843904)
    	at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
    	at java.base/java.nio.Buffer.position(Buffer.java:293)
    	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1094)
    	at jadx.plugins.input.dex.sections.SectionReader.absPos(SectionReader.java:82)
    	at jadx.plugins.input.dex.sections.debuginfo.DebugInfoParser.process(DebugInfoParser.java:84)
    	at jadx.plugins.input.dex.sections.DexCodeReader.getDebugInfo(DexCodeReader.java:118)
    	at jadx.core.dex.nodes.MethodNode.getDebugInfo(MethodNode.java:626)
    	at jadx.core.dex.visitors.debuginfo.DebugInfoAttachVisitor.visit(DebugInfoAttachVisitor.java:39)
     */
     
    @Override // androidx.fragment.app.Fragment  
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {  
        return null;  
    }  
    `

**Comment by jpstotz** [comment] 2024-09-11 11:15
@draekko Thanks for providing a sample app. Which Jadx version have you used when the posted error occurred? 

I wasn't able to reproduce your problem using Jadx 1.5.0 and also not with latest stable version decompiling `androidx.fragment.app.Fragment` of `CoospoRide_2.5.31_APKPure.apk` (SHA-1 hash 9F8D9CFED84E2514EBE644235B289E26A914C41D).

**Comment by draekko** [comment] 2024-09-11 12:52
I tried 1.5.0 release which i've been using since it was released and tried the latest unstable build this morning.

Java says this

openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)

Using it on latest Ubuntu 24.04.1 LTS

**Comment by draekko** [comment] 2024-09-11 12:54
hmmm seems to have a different hash as the one i extracted off the device which i got it via the play store using aurora store for v2.5.31.

7a14391791d3d9666bc784083dabd109f1a3aa8f

**Comment by draekko** [comment] 2024-09-11 13:04
Does jadx use JAVA_HOME or does it use the default path for the jdk?

**Comment by jpstotz** [comment] 2024-09-11 13:11
Verified - com.onecoder.coosporide.main.ChartFragment causes multiple errors like java.lang.IllegalArgumentException: newPosition > limit: (67042709 > 8843904) in APK CoospoRide_2.5.31_APKPure.apk (SHA-1 hash 9F8D9CFED84E2514EBE644235B289E26A914C41D) from https://apkpure.com/coosporide/com.onecoder.coosporide

**Comment by jackwpa** [comment] 2024-09-11 15:49
It is likely to be caused by NOP padding in the method bytecode, after the return instruction. It can be seen below with JEB, with the "Show instructions in gap" option enabled.

![image](https://github.com/user-attachments/assets/58895cbd-adf7-49c4-a273-0a62a477a89b)

**Comment by skylot** [comment] 2024-09-11 19:17
@draekko, @jpstotz thanks for sample and issue confirm

This issue caused by incorrect debug info offset in dex method code section.
(Check DEX format docs https://source.android.com/docs/core/runtime/dex-format#code-item for `debug_info_off` field.)
Looks like it was corrupted intentionally to disrupt decompilation or dissemble.
Anyway, such incorrect data clearly reported by ApkTool/Smali like this:
```
Lcom/onecoder/coosporide/main/ChartFragment;->createCircleGradientDrawable(II)Landroid/graphics/drawable/Drawable;: Invalid debug offset
```
So I also commit a similar check and now instead of error with stacktrace, simple warning is added:
```java
    /* JADX WARN: Invalid debug info offset */
    public final Drawable createCircleGradientDrawable(int startColor, int endColor) {
        return null;
    }
```
Funny that here argument names comes from Kotlin metadata, which are not removed :rofl:

**Closed by skylot** 2024-09-11 19:17 UTC
Labels: bug, no-reply, Core, no-sample

**Comment by draekko** [comment] 2024-09-12 10:06
Just tried apktool and all the smali code is nop'ed out as jackpwa mentioned, any suggestions on how i might go about to retrieve the code? Thanks in advance

**Comment by skylot** [comment] 2024-09-12 17:02
> any suggestions on how i might go about to retrieve the code?

@draekko looks like this is not possible using only static analysis tools like jadx, so you also need a dynamic/runtime tool like frida to catch dex files restored/decrypted at runtime. ApkId report that this apk uses `Ijiami` packer, so you can try to search guides to fight it.

**Comment by draekko** [comment] 2024-09-13 16:56
Thanks for the suggestion, will look into them.

**Comment by TiTiKy441** [comment] 2025-02-06 19:45
Hi, my first time trying jadx. Been trying to decomplie a dex file that was purposely made for it to be harder to decomplile (second stage of monokle spyware). 

Downloaded jadx sources and build it on my machine. Tried opening this file with a newly build version, used default properties, except no chechsum check, got 
```
java.lang.IllegalArgumentException: newPosition > limit: (305419896 > 5506993)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:352)
	at java.base/java.nio.Buffer.position(Buffer.java:327)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1557)
	at jadx.plugins.input.dex.sections.SectionReader.absPos(SectionReader.java:82)
	at jadx.plugins.input.dex.sections.DexHeader.readMapList(DexHeader.java:56)
	at jadx.plugins.input.dex.sections.DexHeader.<init>(DexHeader.java:52)
	at jadx.plugins.input.dex.DexReader.<init>(DexReader.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:83)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:66)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:49)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:44)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:42)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:38)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:156)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:120)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:75)
	at jadx.gui.ui.MainWindow.lambda$loadFiles$3(MainWindow.java:579)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

Is there something I need to enable in the settings to skip this error?

**Comment by skylot** [comment] 2025-02-06 19:51
> Is there something I need to enable in the settings to skip this error?

No, jadx just failed to parse this dex :rofl:
@TiTiKy441 please open a new issue and attach a mentioned dex :slightly_smiling_face:
