### ISSUE TITLE
Deobfuscation does not know android.support.v4 and similar names

### ISSUE THREAD

**Issue by Sonic-Amiga** [skylot/jadx#765] opened 2019-10-17 10:22 UTC
I am deobfuscating an app containing android.support library, whose classes are obfuscated as a, b, etc. Automatic deobfuscator doesn't recognize android.support.vX as a valid name and renames vX to autogenerated unique name like C0001vX

**Comment by jpstotz** [comment] 2019-10-17 10:51
What name would you have expected? 
Note that Jadx does not contain functionality for library identification. Therefore Jadx is is not able to regenerate the original class names. The deobfuscation feature is mainly for classes that has been obfuscated in a way that makes them hard to read by humans.

**Comment by skylot** [comment] 2019-10-17 13:33
Duplicate of #66

**Closed by skylot** 2019-10-17 13:33 UTC
Labels: Core, bug

**Comment by Sonic-Amiga** [comment] 2019-10-17 19:25
Well, this can be seen as a small subset of #66, but this one is easy to fix. Something like if(class_name.startsWith("android.support.v") ) deobfuscate=false;

**Comment by Sonic-Amiga** [comment] 2019-10-17 19:30
Just to be more clear about my case. "v4" part is preserved and not changed, so obfuscated names look like "android. support. v4.a", "android.support.v4.b", etc. And deobfuscator does not recognize "android.support.v" as legitimate, and replaces "v4" with generated name, which should not be done.
