### ISSUE TITLE
[core] Jadx Fails to Infer Types for Null Variables

### ISSUE THREAD

**Issue by xxh160** [skylot/jadx#2090] opened 2024-01-25 21:19 UTC
### Issue details

I've encountered a type inference issue in Jadx when dealing with null variables of different types. The decompiler seems to struggle with correctly inferring the types and ends up producing code with "??" as the type.

### Relevant log output or stacktrace

```java
./out/sources/defpackage/Demo.java:7: error: illegal start of expression
        ?? r0 = 0;
        ^
./out/sources/defpackage/Demo.java:7: error: illegal start of expression
        ?? r0 = 0;
         ^
./out/sources/defpackage/Demo.java:7: error: : expected
        ?? r0 = 0;
                 ^
3 errors
```

### Provide sample and class/method full name

Consider the following Java code:

```java
class T2 {
    public void foo2() {
    }
}

class T1 {
    public void foo1() {
    }
}

public class Demo {
    public void demo() {
        ((T1) null).foo1();
        // Additional code here...
        ((T2) null).foo2();
    }
}
```

In the demo method of the Demo class, methods foo1 of T1 and foo2 of T2 are called. However, after decompilation with Jadx, the output transforms unexpectedly:

```java
/* renamed from: Demo  reason: default package */
public class Demo {
    /* JADX WARN: Type inference failed for: r0v0, types: [T1, T2] */
    public void demo() {
        ?? r0 = null;
        r0.foo1();
        r0.foo2();
    }
}
```

### Jadx version

1.4.7

**Comment by skylot** [comment] 2024-01-25 22:12
@xxh160 thanks, that is weird case :slightly_smiling_face:
Can you share smali code of your demo method?
Because I got slightly different result with another issue :rofl:
```java
    public void demo() {
        T2 t2 = null;
        T1 t1 = (T1) t2;
        t1.foo1();
        T2 t22 = t2;
        t22.foo2();
    }
```
Also, funny that direct java bytecode input (just `.class`) produce correct result this time :tada:

**Comment by xxh160** [comment] 2024-01-26 22:30
I'd like to provide two additional examples that further demonstrate the issue.

Example 1:
Original Java Code:

```java
interface I1 {
    void foo1();
}

interface I2 extends I1 {
    I1 foo2();
}

public class Demo2 {
    public void demo(boolean b) {
        ((b) ? ((I2) null).foo2() : (I1) null).foo1();
    }
}
```

Decompiled Output by Jadx:

```java
public class Demo2 {
    public void demo(boolean z) {
        I2 i2 = null;
        if (z) {
            i2 = i2.foo2();
        }
        i2.foo1();
    }
}
```

Error Encountered:

```txt
./out/sources/defpackage/Demo2.java:8: error: incompatible types: I1 cannot be converted to I2
    i2 = i2.foo2();
                ^
1 error
```

Example 2:
Original Java Code:

```java
interface I1 {
    void foo1();
}

interface I2 extends I1 {
    I1 foo2();
}

public class Demo3 {
    public void demo(boolean b) {
        I1 i1 = (I1) null;

        if (b) {
            i1 = ((I2) null).foo2();
        }

        i1.foo1();
    }
}
```

Decompiled Output by Jadx:

```java
public class Demo3 {
    public void demo(boolean z) {
        (z ? r0.foo2() : null).foo1();
    }
}
```

Error Encountered:

```txt
./out/sources/defpackage/Demo3.java:6: error: cannot find symbol
    (z ? r0.foo2() : null).foo1();
         ^
  symbol:   variable r0
  location: class Demo3
1 error
```

**Comment by xxh160** [comment] 2024-01-26 22:47
I have compiled the class files, classes.dex, and smali files into a single compressed file. Additionally, I would like to mention that I used the `d8` tool from the 33.0.1 version of `build-tools`. Hopefully, this will be of assistance.

[classes.zip](https://github.com/skylot/jadx/files/14069920/classes.zip)

I also want to provide two additional examples that further demonstrate the issue.

Example 1:
Original Java Code:

```java
interface I1 {
    void foo1();
}

interface I2 extends I1 {
    I1 foo2();
}

public class Demo2 {
    public void demo(boolean b) {
        ((b) ? ((I2) null).foo2() : (I1) null).foo1();
    }
}
```

Decompiled Output by Jadx:

```java
public class Demo2 {
    public void demo(boolean z) {
        I2 i2 = null;
        if (z) {
            i2 = i2.foo2();
        }
        i2.foo1();
    }
}
```

Error Encountered:

```txt
./out/sources/defpackage/Demo2.java:8: error: incompatible types: I1 cannot be converted to I2
    i2 = i2.foo2();
                ^
1 error
```

Example 2:
Original Java Code:

```java
interface I1 {
    void foo1();
}

interface I2 extends I1 {
    I1 foo2();
}

public class Demo3 {
    public void demo(boolean b) {
        I1 i1 = (I1) null;

        if (b) {
            i1 = ((I2) null).foo2();
        }

        i1.foo1();
    }
}
```

Decompiled Output by Jadx:

```java
public class Demo3 {
    public void demo(boolean z) {
        (z ? r0.foo2() : null).foo1();
    }
}
```

Error Encountered:

```txt
./out/sources/defpackage/Demo3.java:6: error: cannot find symbol
    (z ? r0.foo2() : null).foo1();
         ^
  symbol:   variable r0
  location: class Demo3
1 error
```

**Comment by skylot** [comment] 2024-01-27 21:29
@xxh160 thanks for a sample :+1:
Turns out smali in your dex is different in a really weird way:
```
    const/4 v0, 0x0
    move-object v1, v0
    check-cast v1, LT1;
    invoke-virtual {v0}, LT1;->foo1()V
    move-object v1, v0
    check-cast v1, LT2;
    invoke-virtual {v0}, LT2;->foo2()V
```
Because it invokes `check-cast` on register, which is not used later.
This makes it much harder to inline/connect with correct `invoke`.

Just to compare, this is the code I got with dx:
```
    const/4 v1, 0x0
    move-object v0, v1
    check-cast v0, LT1;
    invoke-virtual {v0}, LT1;->foo1()V
    check-cast v1, LT2;
    invoke-virtual {v1}, LT2;->foo2()V
```

**Comment by xxh160** [comment] 2024-01-29 02:03
@skylot Thanks! So does this mean the issue might be related to the compiler on my OS, rather than with Jadx itself?

**Comment by skylot** [comment] 2024-01-29 16:34
>  So does this mean the issue might be related to the compiler

No. Result bytecode is fine and semantically correct.
Code variations come mostly because test case is small and synthetic (should not appear in real code) because it just throws NPE. And the latest `d8` version (from 34 build tools) just do it by replacing invoke with `throw null`.

Anyway, restoring missing/incorrect casts is an issue in jadx that should be fixed, and I am working on it right now :slightly_smiling_face:

**Comment by skylot** [comment] 2024-02-10 18:14
Fixed.
I apply more aggressive `null` inlining and insertion of additional casts.
Also, most of the changes in referenced commit are done to fix incorrect rollback during type updates. These changes quite impactful so regressions are expected :slightly_frowning_face:

**Closed by skylot** 2024-02-10 18:14 UTC
Labels: bug, Core
