### ISSUE TITLE
[gui] Launch4j created Jadx-version does not show classes from contained DEX file(s)

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#949] opened 2020-06-10 10:15 UTC
The current builds of Jadx-gui.exe created via `gradlew clean createExe` are defect (tested with the provided unstable exe version https://bintray.com/skylot/jadx/download_file?file_path=jadx-gui-1.1.0-b1301-65553c15.exe as well as self-compiled one). 

If you use one of this versions it loads APK files fast but the class tree afterwards only contains the generated `R` class.

The shown log does not show any errors:

```
INFO : output directory: Amazon Kindle_v8.24.1.0_apkpure.com
INFO : loading ...
INFO : Can't find 'R' class in app package: com.amazon.kindle
INFO : App 'R' class not found, put all resources ids into : 'com.amazon.kindle.R'

```

![jadx](https://user-images.githubusercontent.com/924885/84256306-06ccc480-ab14-11ea-8157-bee9a3fc1b79.png)

**Comment by jpstotz** [comment] 2020-06-11 13:52
@skylot Thanks for fixing this problem. The new unstable version now correctly loads all classes again.

While playing around with the new unstable version I noticed something strange: On my Windows system the jadx-gui-dev.exe versions now ignore the configured maximum heap size. No matter what is configured in [build.gradle](https://github.com/skylot/jadx/blob/master/jadx-gui/build.gradle#L70-L71) Jadx ends up with 1GB maximum heap (on a system with 16GB RAM installed). 

Only if I completely disable the heap configuration of Launch4j (results in 3.99GB max heap) or if I create a `jadx-gui-dev.l4j.ini` and override the max heap value using this config file I can get a maximum heap size that is different to 1GB. 

When I start jadx-gui-dev.exe in debug mode using `jadx-gui-dev.exe --l4j-debug` I get the following log:

```
Version:	3.12
CmdLine:	C:\IntelliJ-projects\jadx\jadx-gui\build\launch4j\jadx-gui-dev.exe --l4j-debug
WOW64:		yes
Working dir:	C:\IntelliJ-projects\jadx\jadx-gui\build\launch4j\.
Java min ver:	1.008.000
Java max ver:	
Substitute:	JAVA_HOME = C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\
Bundled JRE:	C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\
Check launcher:	C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\javaw.exe (OK)
Heap -Xms:	Requested 0 MB / 5%, Available: 9723 MB, Heap size: 486 MB
Heap limit:	Reduced 6806 MB heap size to 32-bit maximum 1024 MB
Heap -Xmx:	Requested 4096 MB / 70%, Available: 9723 MB, Heap size: 1024 MB
Main class:	jadx.gui.JadxGUI
Add classpath:	lib\jadx-gui-dev-all.jar
Launcher:	C:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot\bin\javaw.exe
Launcher args:	-Xms486m -Xmx1024m -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC -classpath "C:\IntelliJ-projects\jadx\jadx-gui\build\launch4j\jadx-gui-dev.exe;lib\jadx-gui-dev-all.jar" jadx.gui.JadxGUI
Args length:	207/32768 chars
Exit code:	0
```

It seems like for an unknown reason launch4j thinks that the used JRE is a 32bit one. 

Looking at the available configuration options I found out that I can avoid this problem by adding the configuration option `bundledJre64Bit = true`. Afterwards the created Launch4j exe wrapper again applies the correct heap size (I will provide a PR for that). 

After some more tests tests I identified commit c62039f327c7cb0628b4ecd8a828c72f71293722 as the problem source.

**Comment by skylot** [comment] 2020-06-11 14:01
@jpstotz I found a root cause of the issue: during shadow jar build plugins service files overwrite each other and only one plugin left to load. I fix this by the additional option to shadowJar plugin.

**Comment by skylot** [comment] 2020-07-11 08:40
Looks like all issues fixed here, closing.

**Closed by skylot** 2020-07-11 08:40 UTC
Labels: GUI, bug
