### ISSUE TITLE
NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" 

### ISSUE THREAD

**Issue by jietlee** [skylot/jadx#2286] opened 2024-09-21 09:31 UTC
### Issue details

Jadx version : 1.5.0
Java version : 21.0.3
Java VM      : Eclipse Adoptium OpenJDK 64-Bit Server VM
Platform     : Windows 11 (10.0 amd64)
Max heap size: 4096 MB
```
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null
	at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$2.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Jadx version

1.5.0

### Java version

21.0.3

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment] 2024-09-21 10:17
Duplicate of #1657

Possible workaround: Enable `Preferences -> Other -> Use alternative file dialog` option, this will use another file open dialog implementation.

**Closed by skylot** 2024-09-21 10:17 UTC
Labels: bug, GUI
