### ISSUE TITLE
[core] UnsupportedOperationException in addResourceFields

### ISSUE THREAD

**Issue by ghostrider-reborn** [skylot/jadx#1645] opened 2022-08-17 16:56 UTC
Adding R class fields names to java code fails when decompiling a system apk from Android 13 (API 33).
Occurs in latest stable version (1.4.3) as well as nightly (1.4.3.63-127f0ecf).

```
$ jadx SystemUIGoogle.apk
INFO  - loading ...
ERROR - Failed to parse '.arsc' file
java.lang.UnsupportedOperationException: null
        at java.base/java.util.AbstractList.add(AbstractList.java:153)
        at java.base/java.util.AbstractList.add(AbstractList.java:111)
        at jadx.core.utils.android.AndroidResourcesUtils.lambda$addResourceFields$2(AndroidResourcesUtils.java:132)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at jadx.core.utils.android.AndroidResourcesUtils.addResourceFields(AndroidResourcesUtils.java:126)
        at jadx.core.utils.android.AndroidResourcesUtils.searchAppResClass(AndroidResourcesUtils.java:52)
        at jadx.core.dex.nodes.RootNode.processResources(RootNode.java:195)
        at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:175)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:122)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
INFO  - processing ...
ERROR - finished with errors, count: 7 
$ jadx --version
1.4.3.63-127f0ecf
$ java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

Link to the apk: https://dumps.tadiphone.dev/dumps/google/generic/-/raw/redfin-user-13-TP1A.220624.014-8819323-release-keys/system_ext/priv-app/SystemUIGoogle/SystemUIGoogle.apk

**Comment by jpstotz** [comment] 2022-08-17 17:19
The problem is that `ClassNode.fields` is initialized using `fieldsConsumer.getResult()` which can return an `Collections.emptyList()` which does not allow adding fields. 

Changing the call in `AndoridresourceUtils.addResourceFields` from `typeCls.getFields().add(newResField);` to `typeCls.addField(newResField);` would be the first step and then changing `ClassNode.addField` to first check if the current field list is the empty singleton the second.

The question that I can not answer is: At the moment the `ClassNode.fields` is identical to the fieldsConsumer list, that means adding an entry to the fields list also adds it to the fieldConsumer. Is this necessary/required or can we simply assign a new list to `ClassNode.fields`?

I have mentioned changes are here: https://github.com/jpstotz/jadx/commit/fdd647df562c0290e4e2ff335804108a1167d75b

**Comment by skylot** [comment] 2022-08-17 18:03
@jpstotz thanks for check and fix!
> or can we simply assign a new list to ClassNode.fields

Sure, `fieldsConsumer` is a temporary object for holding results and should be GC after initial load.

Side note: I don't like using list getter for adding item, I wish java have `ImmutableList` interface 🙂
And in addition, I even have a weird set of methods like [`safeAdd`](https://github.com/skylot/jadx/blob/6e5899c654e5eb0722e7e0882205782955ec174f/jadx-core/src/main/java/jadx/core/utils/ListUtils.java#L105-L113) to handle adding into empty immutable list. So you may found code like this: :rofl:
```java
cls.setDependencies(ListUtils.safeAdd(cls.getDependencies(), outerCls.getTopParentClass()));
```

**Comment by jpstotz** [comment] 2022-08-18 13:58
@skylot The PR is ready that fixes this issue. But while testing the linked APK file I noticed that it causes an StackOverflowError in `jadx.api.JavaClass.getTopParentClass` (happens automatically when you decompile the code).

**Comment by skylot** [comment] 2022-08-18 15:20
@jpstotz thank you :+1:
> it causes an StackOverflowError in jadx.api.JavaClass.getTopParentClass

I commit a fix for this :slightly_smiling_face:

**Closed by skylot** 2022-08-18 15:20 UTC
Labels: bug, Core
