### ISSUE TITLE
java.lang.NegativeArraySizeException: -1332740096

### ISSUE THREAD

**Issue by sysiiii** [skylot/jadx#1691] opened 2022-09-29 03:13 UTC
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.4
* Java version: 18.0.2.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 14696 MB

```
java.lang.NegativeArraySizeException: -1332740096
	at io.github.hqktech.JDWP.decodeRaw(JDWP.java:402)
	at io.github.hqktech.JDWP$JdwpString.decode(JDWP.java:7475)
	at io.github.hqktech.JDWP$ReferenceType$MethodsWithGeneric.decode(JDWP.java:2415)
	at jadx.gui.device.debugger.SmaliDebugger.getMethodSignatureInternal(SmaliDebugger.java:998)
	at jadx.gui.device.debugger.SmaliDebugger.access$500(SmaliDebugger.java:83)
	at jadx.gui.device.debugger.SmaliDebugger$4.lambda$onMethodEntry$0(SmaliDebugger.java:412)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by jpstotz** [comment] 2022-09-29 12:53
Duplicate of https://github.com/skylot/jadx/issues/1524 and potentially also of https://github.com/skylot/jadx/issues/1471. For the latter a patch exists but it the library maintainer has not yet accepted it.

**Closed** 2022-09-29 20:33 UTC
