### ISSUE TITLE
Unable to decompile YouTube Music APK

### ISSUE THREAD

**Issue by RenautMestdagh** [skylot/jadx#2066] opened 2023-12-23 20:00 UTC
### Issue details

error when opening youtube music apk

### Relevant log output or stacktrace

```java
Jadx version : dev
Java version : 1.8.0_392
Java VM      : Oracle Corporation OpenJDK 64-Bit Server VM
Platform     : Linux (5.15.133.1-microsoft-standard-WSL2 amd64)
Max heap size: 5352 MB
Program args : -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true

java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at jadx.plugins.input.dex.sections.SectionReader.duplicate(SectionReader.java:60)
	at jadx.plugins.input.dex.sections.SectionReader.<init>(SectionReader.java:34)
	at jadx.plugins.input.dex.DexReader.<init>(DexReader.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:84)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:67)
	at jadx.plugins.input.dex.DexFileLoader.lambda$collectDexFromZip$2(DexFileLoader.java:92)
	at jadx.api.plugins.utils.ZipSecurity.lambda$readZipEntries$0(ZipSecurity.java:124)
	at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:103)
	at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFromZip(DexFileLoader.java:90)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:73)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:128)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:112)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Jadx version

1.4.7

**Comment by skylot** [comment] 2023-12-23 20:04
Duplicate of #1607
Check this comment: https://github.com/skylot/jadx/issues/1607#issuecomment-1207410972

**Closed by skylot** 2023-12-23 20:04 UTC
Labels: bug, Core
