### ISSUE TITLE
[core] Deobfuscate file resources

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#996] opened 2020-10-25 03:28 UTC
Tested on Google Chrome APK (latest version). Jadx unzips them with original names
<img src="https://user-images.githubusercontent.com/15173437/97098017-f9f2dc80-1680-11eb-8ace-347c4cd0f4bd.png" width="150px">

However apktool saves when with name `res/{type}/{name}`, e.g. `res/xml/somefile.xml`
<img src="https://user-images.githubusercontent.com/15173437/97098206-e779a280-1682-11eb-93ff-a62133c90204.png" width="200px">

**Comment by alissonlauffer** [comment] 2020-10-25 04:11
This is a duplicate of my issue (https://github.com/skylot/jadx/issues/952), but I think I haven't explained its purpose clearly. Should I close my ticket and use this one instead?

**Comment by sergey-wowwow** [comment] 2020-10-25 04:21
@alissonlauffer 
I'm trying to finish a commit. In short, each `ResourceEntry` with `ResourceEntry.simpleValue.dataType == 3` refers to strings array with `data` index. So in file `ResourcesSaver` we can actually ignore resource files, but consider resource entries pointing to those files, and save them with deobfuscated names

**Closed** 2020-10-25 19:08 UTC
Labels: Core, bug
