### ISSUE TITLE
[core]Incomplete search results and white screen for decompiled results

### ISSUE THREAD

**Issue by bhwxha** [skylot/jadx#1580] opened 2022-07-18 05:24 UTC
link:https://drive.google.com/file/d/1yEzUlBNPa8Jm7H2QozTKfgHM6q47VOuV/view?usp=sharing

A search for `tv_value` produced only these results:

![image](https://user-images.githubusercontent.com/107301547/179449153-0e3a3ce0-b1bc-48c6-9a37-503dbb913445.png)

However, in `com.yuanrenxue.match2022.adapter.RefreshHeadViewAdapter.OooO0Oo(@NonNull final RecyclerViewHolder recyclerViewHolder, int i, OooO0OO oooO0OO)` also exists `tv_value`, the search results are incomplete.

![image](https://user-images.githubusercontent.com/107301547/179449344-07dfde0c-be45-4abe-bc21-2f0698955b2f.png)

Also, the last result I got from the previous global search for `tv_value`, when I clicked in, was a white screen.

![image](https://user-images.githubusercontent.com/107301547/179449464-881996bd-67f8-436d-855d-893d8e105a99.png)

**Comment by bhwxha** [comment] 2022-07-19 07:43
It's strange, because in my case, the bug has always existed.
I use is the latest jadx, source code version: c27f2ba, download the source code and compile it yourself to use.
I'll upload my jadx zip file here:https://drive.google.com/file/d/1vjURdNV01g-dgB-PxoefVcY0Couw0XDd/view?usp=sharing
jadx decompiled this apk to get the info level logs:https://drive.google.com/file/d/16asu2GRE33gjg9Iom9nPSgGpyODI3LFH/view?usp=sharing
My jadx configuration:https://drive.google.com/file/d/1UNTfeNu50qaCrahEhyb9cCqJGLcH_Wlv/view?usp=sharing

windows11
java -version(Use java8 to compile and use jadx)
```
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
```

**Comment by skylot** [comment] 2022-07-19 19:12
@bhwxha thanks for sharing jadx config! Turns out this issue can be reproduced only with `Inline anonymous classes` option.
I found the cause and committed a fix :+1:

**Closed by skylot** 2022-07-19 19:12 UTC
Labels: bug, Core, can't reproduce

**Comment by bhwxha** [comment] 2022-07-20 04:19
@skylot Thank you for the fix, the above bug has been solved.

However, I have found suspected new bugs:
Lookup reference to method `com.yuanrenxue.match2022.adapter.RefreshHeadViewAdapter.OooO0Oo(@NonNull final RecyclerViewHolder recyclerViewHolder, int i, OooO0OO oooO0OO)`, the result is 0.

![image](https://user-images.githubusercontent.com/107301547/179895473-d6d9c643-39e9-41d2-a93d-68315d232ef0.png)

jeb:

![image](https://user-images.githubusercontent.com/107301547/179895902-6e9c9205-7c53-4a99-b247-6b78ad0480f0.png)

**Comment by skylot** [comment] 2022-07-20 14:22
@bhwxha I committed a fix, but the actual issue is slightly different.
The method name here is different, because it was inlined/merged with a bridge method, so jadx usage should show usage of that bridge method (I fixed that, also override annotation was missing). So if you want to compare with JEB, I suggest disabling all inline options in preferences (`Inline methods` for this case), this will show both methods, and it will be easier to compare usages.

**Comment by bhwxha** [comment] 2022-07-21 07:34
> @bhwxha I committed a fix, but the actual issue is slightly different. The method name here is different, because it was inlined/merged with a bridge method, so jadx usage should show usage of that bridge method (I fixed that, also override annotation was missing). So if you want to compare with JEB, I suggest disabling all inline options in preferences (`Inline methods` for this case), this will show both methods, and it will be easier to compare usages.

Ok, thanks for the fix.
