### ISSUE TITLE
Incorrect GUI rendering

### ISSUE THREAD

**Issue by MrIkso** [skylot/jadx#581] opened 2019-04-10 13:17 UTC
Prewiee bug in video
https://drive.google.com/open?id=1n4cvV6k4xpbWuO4GoEzGX6NUhJiUSC8I

**Comment by jpstotz** [comment] 2019-04-10 14:40
The video does not work - it does not start. Please provide a textual description of your problem.

**Comment by asashour** [comment] 2019-04-10 17:36
I understand the issue is: the line numbers in the GUI are initially incorrect (possibly because they are the numbers in the original code), and on clicking the side bar, the numbers are rearranged, so they match what is in the current file.

**Comment by asashour** [comment] 2019-04-11 09:50
Duplicate of #186

**Comment by skylot** [comment] 2019-04-11 10:06
For me, this looks like a render (or paint) problem (notice "import" artifacts in line number area). I already tried to fix this in [commit](https://github.com/skylot/jadx/commit/7e8435ccebc6c9003f509667eb3cf0a1c05681a9) for #404, but apparently, it is not fixed yet.

**Comment by asashour** [comment] 2019-04-11 10:16
I have difficulty producing this with `master` on Windows. Also, there is `New version v0.9.0 available!`, which I don't have.

**Comment by skylot** [comment] 2019-04-11 10:24
@asashour I also can't reproduce this, so it is hard to make a fix :(

> `New version v0.9.0 available!`

Yeah I know, it appear on `dev` version. But by default this version check is disabled in preferences ))

**Closed** 2021-08-06 09:55 UTC
Labels: bug, GUI
