### ISSUE TITLE
Some classes are kept in the unnamed package

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#474] opened 2019-03-16 22:51 UTC
Hi, 
Please check the following code
```java
package com.paypal.merchant.client.features.configurationloader.ui;

public class ConfigurationLoaderActivity extends C8021By {
```
where ``` C8021By ``` is a class in the root (default/unnamed package), but I believe it should be moved to ``` p000 ```, because it's illegal code and all references to actual class are lost:
> C8021By cannot be resolved to a type

APK: https://drive.google.com/file/d/1_8--CfspEnugSTGjF3Krkt4r3SEV6vq7/view?usp=sharing

**Comment by sergey-wowwow** [comment] 2019-03-25 21:04
@skylot,
Don’t you have time to fix that bug? It breaks the class hierarchy and causes many errors in important classes :/

**Comment by skylot** [comment] 2019-03-26 14:07
@sergey-wowwow I can't reproduce your issue :(
Can you provide all arguments and options you pass to jadx?
Also, try latest master branch I recently merged type-inference-wip branch into it, so maybe issue already fixed.

**Comment by skylot** [comment] 2019-03-26 14:17
Weird, I check both cli and gui with different options, I can't reproduce it.
Do you have `Force rewrite deobfuscation map file` option enable, maybe map file saved from previous versions?

**Comment by sergey-wowwow** [comment] 2019-03-26 14:18
@skylot 
And arguments for jadx-cli
> ./bin/jadx/bin/jadx.bat --no-replace-consts --show-bad-code --threads-count 4 --deobf --deobf-min 2 --no-imports --output-dir TEST com.paypal.merchant.client_2019.03.07.apk

**Comment by skylot** [comment] 2019-03-26 14:23
@sergey-wowwow please try with `--deobf-rewrite-cfg` option maybe it will help

**Comment by sergey-wowwow** [comment] 2019-03-26 14:27
@skylot 
It doesn't, the same on Mac and Windows, I run
> .\bin\jadx\bin\jadx.bat --no-replace-consts --show-bad-code --threads-count 4 --deobf --deobf-min 2 --no-imports --deobf-rewrite-cfg --output-dir TEST com.paypal.merchant.client_2019.03.07.apk

Result
![2019-03-26_1726](https://user-images.githubusercontent.com/15173437/55005055-652f8500-4fec-11e9-922b-94c94e3a5c78.png)

**Comment by sergey-wowwow** [comment] 2019-03-26 15:31
@skylot 
Were you able to reproduce that? Or maybe I should try to find different examples?

**Comment by skylot** [comment] 2019-03-26 15:37
Sorry, I don't. I was checking code, but still, have no idea how that happens.
I will try to check it on Windows (previously I check on Linux).
BTW, which java version do you use?

**Comment by sergey-wowwow** [comment] 2019-03-26 15:41
javac says 11.0.1

Also the bug is reproducible for Google Chrome:
https://drive.google.com/file/d/1esYMOzJ5Z9DMY09ndOk-2qo8xAXRt0Uf/view?usp=sharing

**Comment by asashour** [comment] 2019-03-26 15:43
I am with 1.8_202 on Windows.

**Comment by skylot** [comment] 2019-03-26 15:49
I got it! Issue reproduces than file system is not case sensitive )) Problem code [here](https://github.com/skylot/jadx/blob/e1f4955286f73a6ca4525fc27b11fd02106f7f08/jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java#L58).
Thanks, guys!

**Comment by skylot** [comment] 2019-03-26 16:30
I made a quick fix, without a test for now, because I need to make some refactoring to allow change FS case sensitivity checks result from tests.

**Closed by skylot** 2019-03-26 16:30 UTC

**Comment by sergey-wowwow** [comment] 2019-03-26 16:51
@skylot 
Thanks! If something is wrong (but all example apps are decompiled without such issues now), I will file a new issue
