### ISSUE TITLE
[core] Insane memory leak

### ISSUE THREAD

**Issue by KarmaMod** [skylot/jadx#1266] opened 2021-11-06 15:30 UTC
**Checks before report**
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki
- search existing issues by exception message

**Describe error**
- full name of method or class with error: cc.binmt.signature.Hook

When trying to view Hook class, it will freeze and leaks memory a lot

![image](https://user-images.githubusercontent.com/88159598/140615017-a8376691-4bc1-4b70-8619-511312660cfb.png)

- full java stacktrace (no need to copy method fallback code (commented pseudocode)): N/A
- **IMPORTANT!** attach or provide link to apk file (double check apk version)

https://drive.google.com/file/d/1LMPN7pRXiiNJmvMI_rrX7BdG0b9CTnDh/view

- Jadx Version: 1.2.0.158-4479a3fb

**Comment by skylot** [comment] 2021-11-06 16:05
@KarmaMod thank you for report!
Looks like this issue caused by RSyntaxTextArea lexer which struggle to handle very long array definition in code.
So a quick workaround: export source code and use other editor.
As for actual fix: I am not sure how to fix this for now, possible options:
1. cut big data arrays to some reasonable size, like 10k (this array is ~450k)
2. disable code view after some timeout
3. fix lexer in RSyntaxTextArea

I will try to implement a second option, and maybe a first one.

**Comment by skylot** [comment] 2021-11-06 18:27
I made a quick fix for this case.
According to https://github.com/bobbylight/RSyntaxTextArea/issues/159#issuecomment-815349690 issue caused by very long line, so I just wrap long array definitions. So now this class can be viewed, although many methods decompiled with errors 😕

**Comment by bagipro** [comment] 2021-11-06 18:42
Hey @skylot,

Is there a way to apply this only to jadx-gui, but not to the CLI version?

**Comment by skylot** [comment] 2021-11-06 18:53
> Is there a way to apply this only to jadx-gui, but not to the CLI version?

@bagipro it can be done with additional option. 
You don't like wrapping? Maybe truncating is better? I still not sure about better approach :(

**Comment by bagipro** [comment] 2021-11-08 15:45
@skylot 
Sorry, I just verified and think it's fine. I initially thought that you're dropping some values.

> although many methods decompiled with errors

Can you explain why? This optimization shouldn't break anything

**Comment by skylot** [comment] 2021-11-08 16:09
Oops, just found that exactly same class was already reported in #774.
The previous fix resolve these issues, so I will close them.
Although root cause (i.e. long code lines) still not fixed and need more general approach. I will make another issue to automatically wrap long lines like code formatters do.

**Closed by skylot** 2021-11-08 16:09 UTC
Labels: bug, GUI
