### ISSUE TITLE
[Bug] renaming class to java-integrated class name breaks rename rename feature

### ISSUE THREAD

**Issue by leumasme** [skylot/jadx#1845] opened 2023-04-25 02:16 UTC
When renaming classes in an APK that has obfuscated names, I occasionally find myself mistakenly renaming something in a way that creates a conflict (e.g. rename a class to CharSequence which is an inbuilt class).  
After this happens, I am unable to rename the class back as it is no longer offered (presumably because it's an inbuilt class).  
This is annoying as I then have to close the project, delete the cache, remove the rename entry from the project file and wait for jadx to load the project again.  
Jadx should prevent this from happening in the first place, or at least warn the user.

**Comment by skylot** [comment] 2023-04-25 12:47
> After this happens, I am unable to rename the class back as it is no longer offered

Looks like a bug to me, you should be able to rename class several times regardless of chosen name. I will try to reproduce this and fix. If you can share a sample and a name of a class to rename, it will be very helpful.
Also, which jadx version you use? Latest [unstable version](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) had a lot of changes in renaming code, so it may be worth to check it.

P.S. maybe this is related to issue mentioned in https://github.com/skylot/jadx/issues/1732#issuecomment-1517459581

**Comment by leumasme** [comment] 2023-04-25 16:39
> Also, which jadx version you use?

I was using 1.4.7 (latest available via scoop which scrapes github releases)
I have tried using the linked nightly version now but this ended in the same result.
I don't believe this is apk-specific/situational, but here's a test case that worked:
[Device Info - One Application, All Information v2.9.3.1 by LiuZho Soft](https://m.apkpure.com/device-info-one-application-all-information/com.liuzh.deviceinfo/download)  
Just renaming `a.a` to `CharSequence` demonstrates this issue. The class name changes color to blue (like other internal classes like boolean, int, ...) and it is not possible to rename it back.

**Comment by skylot** [comment] 2023-04-25 21:05
Fixed. For some reason, a lot of [java internal class names](https://github.com/bobbylight/RSyntaxTextArea/blob/2c3f389ad6073873d9b8b56aae59afa1911c4134/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/JavaTokenMaker.flex#L392-L735) were marked as `function` token type instead `identifier`, so jadx just ignores them.

@leumasme please check latest [unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) once again, and thank you for report!

**Closed by skylot** 2023-04-25 21:05 UTC
Labels: bug, GUI, rename
