### ISSUE TITLE
decompile static block throw exception

### ISSUE THREAD

**Issue by sun152121** [skylot/jadx#214] opened 2018-01-24 14:05 UTC
static {
        /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.DecodeException: Load method exception in method: org.cocos2dx.cpp.AppActivity.<clinit>():void
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:116)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:249)
	at jadx.core.ProcessClass.process(ProcessClass.java:31)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:296)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
Caused by: jadx.core.utils.exceptions.DecodeException:  in method: org.cocos2dx.cpp.AppActivity.<clinit>():void
	at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:46)
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:101)
	... 4 more
Caused by: java.lang.IllegalArgumentException: bogus opcode: 0073
	at com.android.dx.io.OpcodeInfo.get(OpcodeInfo.java:1217)
	at com.android.dx.io.OpcodeInfo.getFormat(OpcodeInfo.java:1232)
	at com.android.dx.io.instructions.DecodedInstruction.decode(DecodedInstruction.java:72)
	at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:43)
	... 5 more
*/
        /*
        // Can't load method instructions.
        */
        throw new UnsupportedOperationException("Method not decompiled: org.cocos2dx.cpp.AppActivity.<clinit>():void");
    }

**Comment by skylot** [comment] 2018-01-24 14:09
Please share apk file, without it I can't reproduce this issue

**Comment by skylot** [comment] 2018-01-31 20:02
Ok, I made some fix but can't check it without sample apk.
I'll close this issue for now.

**Closed by skylot** 2018-01-31 20:02 UTC
Labels: no-reply

**Comment by sun152121** [comment] 2018-02-02 02:26
i will post the apk latter!
