### ISSUE TITLE
[gui] When using the rename shortcut key N, there is a probability to enter it

### ISSUE THREAD

**Issue by AdminHcat** [skylot/jadx#1440] opened 2022-04-07 03:13 UTC
When using the rename shortcut key N, there is a probability to enter it

There have been many times. When you press the N key, n appears instead of the original name

The following is the keyboard test software, indicating that the keyboard is pressed only once
![image](https://user-images.githubusercontent.com/50044729/162112321-1d972c1c-839a-400b-b015-d2e51a9a6eea.png)

**Comment by skylot** [comment] 2022-04-07 17:08
@AdminHcat thanks! I also notice this issue, and I agree, it is annoying.
I will try harder to fix this because my previous attempts not succeed, and I still don't understand the cause :slightly_frowning_face:

**Comment by skylot** [comment] 2024-01-05 18:44
Fixed in PR #2075

**Closed by skylot** 2024-01-05 18:44 UTC
Labels: bug, GUI
