### ISSUE TITLE
Decomplication Issue xNot_Found

### ISSUE THREAD

**Issue by dbzdivik** [skylot/jadx#1992] opened 2023-08-29 10:55 UTC
### Issue details

![image](https://github.com/skylot/jadx/assets/7036189/b866defe-08b8-4841-b141-7a2accc2bddc)

As per Image I was trying to decompile an APK and while looking the code I found that NOT_FOUND_0x5 are there in multiple resource file

### Relevant log output or stacktrace

```java
none
```

### Jadx version

1.4.7.221

**Comment by jpstotz** [comment] 2023-08-29 17:41
Thanks for providing the APK. Unfortunately I am not sure if we can fix this problem:

I have tested an old jadx version (before `BinaryXMLStrings` has been introduced in Jadx) -> same output.

Decompiling the APK file with apktool results in the following XML file:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:android="http://schemas.android.com/apk/res/android">
    <item state_enabled="true" 2130970149="true" 2130970150="false">
        <objectAnimator android:duration="@integer/2131492866" android:valueTo="0.0dip" android:valueType="floatType" android:propertyName="elevation" />
    </item>
...
```
Both values seem to be resourceIds, however both values are totally unknown to me. Even checking the list of known resourceIds in `resources.arsc` in `andorid.jar` of API34 of the Android SDK does not reveal an attribute that could fin in here.

In Jadx the string entries `5` and `6` are strings with a length of 0. 

Even searching Google for the two numbers in decimal or hexadecimal format does not get you any result with an Android context. 

Looking at the name of the file name `2130837504.xml` the likeliest explanation is that the APK has ben processed by an obfuscator which has removed the values for those entries as they are not needed by Android at run-time. As Jadx can not reconstruct what has been totally removed without any further reference, 

Therefore I don't see a way to change this behavior.

**Comment by dbzdivik** [comment] 2023-08-29 18:57
Hi @jpstotz 
 Thanks for testing yes I checked with apktool as well for decompilation. the issue is knowing how can I recompile the apk. I wanted to perform some testing.

**Comment by jpstotz** [comment] 2023-08-30 10:08
If you don't want to modify resources you can use `apktool --no-res` to disable resource decompilation so `resources.arsc` is never decompiled and the problem is bypassed.

**Comment by jpstotz** [comment] 2023-09-02 12:50
As the problem is located in the APK and not in Jadx I am closing this issue.

**Closed by jpstotz** 2023-09-02 12:50 UTC
Labels: bug, Core
