### ISSUE TITLE
Prevent zipbomb forged headers attacks

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [skylot/jadx#980] opened 2020-09-22 12:00 UTC
The [isZipBomb](https://github.com/skylot/jadx/blob/1560284831aec19433043f9b818fe4daf46ef607/jadx-plugins/jadx-plugins-api/src/main/java/jadx/api/plugins/utils/ZipSecurity.java#L56) method relies on [ZipEntry.getSize](https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipEntry.html#getSize()) to retrieve the size of an uncompressed entry, but getSize is unreliable to protect against zipbomb attacks, indeed, it gets the size from zip file headers which can be forged by an attacker.

For instance, this file [zipBombForgedHeaders.zip](https://github.com/eric-therond/zipbomb/blob/master/src/main/resources/zipBombForgedHeaders.zip) is the same than [zipBomb.zip](https://github.com/eric-therond/zipbomb/blob/master/src/main/resources/zipBomb.zip) except that the headers have been forged (compressed size of an entry = uncompressed size of an entry):

![image](https://user-images.githubusercontent.com/56015232/93878867-0cbd6e80-fcdb-11ea-868f-afcff10a86b2.png)

![image](https://user-images.githubusercontent.com/56015232/93878828-fca58f00-fcda-11ea-9a2e-561b98d13301.png)

The both archives after being uncompressed take several GiB on the disk.

The first zip (ZipBomb.zip) is correctly blocked by jadx but the second not:
`./build/jadx/bin/jadx ./zipBombForgedHeaders.zip -d zipbombtest2`

![image](https://user-images.githubusercontent.com/56015232/93879132-7b9ac780-fcdb-11ea-962b-29432b8edac1.png)

**Comment by jpstotz** [comment] 2020-09-22 15:53
Do you know how likely ZIP files with manipulated decompressed size values are for non-ZIP-bomb ZIP files?

Because if the uncompressed size value is usually correct (or zero) it would be possible to wrap the `InputStream´ we get from `zipFile.getInputStream(entry)` by a FilterStream that counts the number of bytes read and compares it to the expected decompressed size and a fixed maximum value.

**Comment by eric-therond-sonarsource** [comment] 2020-09-22 16:31
I guess no legit ZIP files should have forged headers, most unzip tools will likely treat these files as corrupt or unzip will not work.

Exactly, for a more precise solution see:
https://wiki.sei.cmu.edu/confluence/display/java/IDS04-J.+Safely+extract+files+from+ZipInputStream
or
https://jira.sonarsource.com/browse/RSPEC-5043

**Comment by jpstotz** [comment] 2020-09-22 16:46
Sorry but the provided mitigation example is bad. Just using `ZipInputStream` may be a solution for Zip bombs, but it has one major disadvantage: **it prevents certain ZIP files for being processed at all**. This happens if the ZIP files contains one entry that uses `STORED` compressor. If you encounter such an entry ZipInputStream is unable to read any entry that follows. Such ZIP files are valid. The limitation that such ZIP archives can't be processed using ZipInputStream is by design.

For details see http://commons.apache.org/proper/commons-compress/zip.html#ZipArchiveInputStream_vs_ZipFile or search for the error `ZipInputStream: only DEFLATED entries can have EXT descriptor`

**Comment by skylot** [comment] 2020-09-22 19:01
@eric-therond-sonarsource thank you for report and samples!
As soon as the ratio of uncompressed/compressed sizes already checked, I think just limit output bytes count as @jpstotz suggested is enough.
Also, in linked solutions, I notice checks for zip entries count - looks like this also need to be added.

**Comment by skylot** [comment] 2020-09-22 20:31
I have made a PR #982. Can someone review it? :)

**Comment by skylot** [comment] 2020-09-27 18:14
PR #982 merged.

@sergey-wowwow can you also check latest commit with zip security enhancements.

**Closed by skylot** 2020-09-27 18:14 UTC
Labels: Core, bug
