### ISSUE TITLE
Invalid anonymous inner class name 

### ISSUE THREAD

**Issue by mingyuan-xia** [skylot/jadx#463] opened 2019-03-08 04:57 UTC
Compiler will generate $N (N as an increment numeric number) for anonymous inner classes. For example:
```
Lcom/zhanhong/RandomNumb/MainActivity$10;
Lcom/zhanhong/RandomNumb/MainActivity$11;
Lcom/zhanhong/RandomNumb/MainActivity$12$1; # an anonymous inner class of an anonymous inner class
```
The dollar sign is valid in the class name. But jadx (0.9.0) simply discards the $ and trims down the name to a simple number, thus generating invalid code, see:
```
public class MainActivity extends android.app.Activity {
     class 10 implements android.view.View.OnClickListener {
```

The fix is to preserve the $ and generate:
```
public class MainActivity extends android.app.Activity {
     class $10 implements android.view.View.OnClickListener {
```

**Comment by skylot** [comment] 2019-03-16 09:53
@mingyuan-xia can you share apk so I can reproduce this issue?
In fact, jadx append 'AnonymousClass' prefix for classes started with a number (see [RenameVisitor#fixClsShortName](https://github.com/skylot/jadx/blob/7654661b776c76abcb97915b46b9d1ace41c7fc9/jadx-core/src/main/java/jadx/core/dex/visitors/RenameVisitor.java#L87)), but in your case something going wrong :(

**Comment by mingyuan-xia** [comment] 2019-03-16 13:15
[Uploading random-number.zip…]()
Here is the sample, APK renamed to zip.

**Comment by mingyuan-xia** [comment] 2019-03-16 13:33
Thanks for the code pointer. I did not notice such visitor before. Yet, I find the case. With fall-back mode, the class names were, as reported, not renamed. With decompilation mode, the two inner classes were listed, but never appear in the decompiled source.

**Comment by skylot** [comment] 2019-03-21 09:33
@mingyuan-xia in fallback mode jadx don't make any renaming or other changes, you just see original bytecode (like smali). For other case: looks like it is already fixed in latest unstable build, please check it.

**Closed by skylot** 2019-03-21 09:33 UTC
