### ISSUE TITLE
jadx.core.utils.exceptions.JadxRuntimeException: Failed to remove code cache for o.cON

### ISSUE THREAD

**Issue by abdilahrf** [skylot/jadx#1535] opened 2022-06-15 11:59 UTC
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.0
* Java version: 11.0.7
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 13420 MB
* Program args: -Xms958m -Xmx13420m -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC

```
jadx.core.utils.exceptions.JadxRuntimeException: Failed to remove code cache for o.cON
	at jadx.gui.utils.codecache.disk.DiskCodeCache.remove(DiskCodeCache.java:196)
	at jadx.gui.utils.codecache.disk.DiskCodeCache.lambda$add$0(DiskCodeCache.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.FileSystemException: E:\xxx\xxxx-21feb22.apk.cache\sources\o\cON.java: The handle is invalid.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1180)
	at jadx.gui.utils.codecache.disk.DiskCodeCache.remove(DiskCodeCache.java:193)
	... 4 more

```

**Comment by jpstotz** [comment] 2022-06-15 12:38
Duplicate of #1503 which has been fixed in Jadx 1.4.1.

**Closed by jpstotz** 2022-06-15 12:38 UTC
