### ISSUE TITLE
`jadx-next` issues

### ISSUE THREAD

**Issue by NebelNidas** [skylot/jadx#1732] opened 2022-11-18 18:43 UTC
Two issues/regressions I found in the `jadx-next` branch:

- While testing the latest commit, I noticed that JADX renamed almost every class to "PG". No idea why, this didn't happen four days ago. Happens regardless of whether or not deobfuscation is enabled or mappings are loaded.
  <details>
  <summary>Example screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/48808497/202776287-99755a79-e7ad-4431-ae01-77c0a588997d.png)
</details>

- Exporting mappings doesn't include the currently open mappings.

**Comment by skylot** [comment] 2022-11-18 20:12
> renamed almost every class to "PG"

Do these classes contains `/* compiled from: PG */`? If yes, just disable `Use source file name as class name alias` option in preferences. Anyway, looks like I need to check other classes names before applying source file name.

> Exporting mappings doesn't include the currently open mappings.

This is weird. I will check this.
And thanks for report these issues :+1:

**Comment by NebelNidas** [comment] 2022-12-08 22:33
> Do these classes contain `/* compiled from: PG */`?

No, see this class for example:
![image](https://user-images.githubusercontent.com/48808497/206580408-2cc33c29-5e34-486d-9252-ce9942e8c603.png)

Weirdly enough, turning off `Use source file name as class name alias` fixed it anyway. Thanks! The APK I use is [YouTube 17.45.36](https://www.apkmirror.com/apk/google-inc/youtube/youtube-17-45-36-release/youtube-17-45-36-android-apk-download/), but I don't think this should really matter.

By the way, turning off the above mentioned option also fixes the mapping export issue!

**Comment by NebelNidas** [comment] 2023-04-14 06:00
@skylot Re:
> Exporting mappings doesn't include the currently open mappings.

I have a fix more or less ready locally, so if you don't rebase in the meantime, hopfully I can submit a PR later today :)

**Comment by NebelNidas** [comment] 2023-04-14 13:12
Hmm, I'm not quite sure how do adjust my changes to your recent changes.

The root issue is as follows: During your initial refactor, you got rid of the persistent `MemoryMappingTree` instance (formerly in [`RootNode`](https://github.com/NebelNidas/jadx/blob/2b24a46830b8de47ad7d98a8f4c94bbf201a535e/jadx-core/src/main/java/jadx/core/dex/nodes/RootNode.java#L69)); now it's just a local variable that can't be accessed from the MappingExporter.

This creates two problems:
- The original mapping namespaces get lost. [My PR](https://github.com/NebelNidas/jadx/blob/2b24a46830b8de47ad7d98a8f4c94bbf201a535e/jadx-gui/src/main/java/jadx/gui/plugins/mappings/MappingExporter.java#L139-L144) vs [jadx-next](https://github.com/skylot/jadx/blob/3d8f98a5a7d6722760c9e65508c9fc7ce17f41bc/jadx-plugins/jadx-rename-mappings/src/main/java/jadx/plugins/mappings/save/MappingExporter.java#L139-L140)
- Currently open mappings aren't exported. [My PR](https://github.com/NebelNidas/jadx/blob/2b24a46830b8de47ad7d98a8f4c94bbf201a535e/jadx-gui/src/main/java/jadx/gui/plugins/mappings/MappingExporter.java#L239-L244) vs [jadx-next](https://github.com/skylot/jadx/blob/3d8f98a5a7d6722760c9e65508c9fc7ce17f41bc/jadx-plugins/jadx-rename-mappings/src/main/java/jadx/plugins/mappings/save/MappingExporter.java#L236-L237)

This can only be solved by passing the MappingExporter the currently open MappingTree instance, but I'm not sure how to best approach this

**Comment by skylot** [comment] 2023-04-14 21:48
@NebelNidas oh, thanks for spot this issue!
I commit a fix to save mapping tree in root attributes storage and return missing code lines :slightly_smiling_face:

**Comment by NebelNidas** [comment] 2023-04-15 07:48
Thank you very much, seems to be fixed :)
Unfortunately though, now that I could test it properly, I've found two other issues:
- Every time you save mappings via "Save mappings as...", a project reload happens. Not sure if this can be done in a nicer way, but to be fair it's a just a minor inconvenience I can live with.
- When you rename package-moved classes, the new name doesn't get picked up by the MappingExporter (it won't get saved). Members work correctly though, it's just the class new name that doesn't get saved. I'll investigate what's happening here and comment my findings once I'm done

**Comment by skylot** [comment] 2023-04-20 21:24
@NebelNidas I fixed first issue and merged `jadx-next` branch into master :slightly_smiling_face:

Also, I have a question about mapping-io library jar currently used in jadx: is it possible to get it from maven repo anyhow? Because it is inconvenient to have libs as dependencies :cry:
I see that your PR https://github.com/FabricMC/mapping-io/pull/19 not yet merged and looks like mapping-io project not active anymore.
So can we switch to your fork, or I can create my own and upload it to maven ?

**Comment by NebelNidas** [comment] 2023-04-21 08:19
> I fixed first issue and merged jadx-next branch into master 🙂

Nice, this means the plugin API is more or less stable now, right? Because we've been looking forward to integrating some auto-naming scripts/plugins into our mapping project 😄

> I see that your PR not yet merged and looks like mapping-io project not active anymore

I'm actively in touch with the maintainers almost everyday on Discord (because of their other projects I'm contributing to), it's just that the guy responsible for mapping-io has been on an extended hiatus for quite a while now. I'm going to poke him again, hopefully he'll merge it. If he does, we can simply use the FabricMC maven, if not, we can fork it, of course :)

Btw, you seem to have introduced another issue recently (unrelated to mappings): When you rename classes, some error seems to happen and the "Rename" context menu entry remains greyed out thereafter (keybind doesn't work either):
<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/48808497/233580153-160ad55d-41a8-4df5-bc23-b268a4ea5e0c.png)
</details>
<details>
  <summary>Log</summary>

```
ERROR: [369] JadxRuntimeException in pass: IfRegionVisitor in method: aaxv.g(int, int, java.lang.String, java.lang.String, com.google.android.libraries.youtube.innertube.model.media.VideoStreamingData, com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel, aams):aari, file: classes.dex
jadx.core.utils.exceptions.JadxRuntimeException: Can't remove SSA var: r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel, still in use, count: 2, list:
  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) from 0x003f: IF  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) == (null com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel)  -> B:26:0x0057 A[HIDDEN]
  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) from 0x0043: PHI (r7v23 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) = 
  (r7v22 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel)
  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel)
 binds: [B:18:0x0042, B:16:0x003f] A[DONT_GENERATE, DONT_INLINE]
	at jadx.core.utils.InsnRemover.removeSsaVar(InsnRemover.java:152)
	at jadx.core.utils.InsnRemover.unbindResult(InsnRemover.java:117)
	at jadx.core.dex.visitors.regions.TernaryMod.makeTernaryInsn(TernaryMod.java:114)
	at jadx.core.dex.visitors.regions.TernaryMod.processRegion(TernaryMod.java:62)
	at jadx.core.dex.visitors.regions.TernaryMod.enterRegion(TernaryMod.java:45)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:67)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverse(DepthRegionTraversal.java:19)
	at jadx.core.dex.visitors.regions.TernaryMod.process(TernaryMod.java:35)
	at jadx.core.dex.visitors.regions.IfRegionVisitor.process(IfRegionVisitor.java:33)
	at jadx.core.dex.visitors.regions.IfRegionVisitor.visit(IfRegionVisitor.java:29)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:26)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:72)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:107)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:375)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:299)
	at jadx.api.JavaClass.load(JavaClass.java:127)
	at jadx.api.JavaClass.getMethods(JavaClass.java:308)
	at jadx.gui.utils.JNodeCache.removeWholeClass(JNodeCache.java:53)
	at jadx.gui.treemodel.JClass.unload(JClass.java:88)
	at jadx.gui.ui.dialog.RenameDialog.refreshClasses(RenameDialog.java:198)
	at jadx.gui.ui.dialog.RenameDialog.lambda$refreshState$4(RenameDialog.java:171)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: [304] JadxRuntimeException in pass: BlockProcessor in method: admg.f():adlr, file: classes.dex
jadx.core.utils.exceptions.JadxRuntimeException: Found unreachable blocks
	at jadx.core.dex.visitors.blocks.DominatorTree.sortBlocks(DominatorTree.java:35)
	at jadx.core.dex.visitors.blocks.DominatorTree.compute(DominatorTree.java:25)
	at jadx.core.dex.visitors.blocks.BlockProcessor.computeDominators(BlockProcessor.java:202)
	at jadx.core.dex.visitors.blocks.BlockProcessor.processBlocksTree(BlockProcessor.java:45)
	at jadx.core.dex.visitors.blocks.BlockProcessor.visit(BlockProcessor.java:39)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:26)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:72)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:107)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:375)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:299)
	at jadx.api.JavaClass.load(JavaClass.java:127)
	at jadx.api.JavaClass.getMethods(JavaClass.java:308)
	at jadx.gui.utils.JNodeCache.removeWholeClass(JNodeCache.java:53)
	at jadx.gui.treemodel.JClass.unload(JClass.java:88)
	at jadx.gui.ui.dialog.RenameDialog.refreshClasses(RenameDialog.java:198)
	at jadx.gui.ui.dialog.RenameDialog.lambda$refreshState$4(RenameDialog.java:171)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
ERROR: [369] JadxRuntimeException in pass: IfRegionVisitor in method: aaxv.g(int, int, java.lang.String, java.lang.String, com.google.android.libraries.youtube.innertube.model.media.VideoStreamingData, com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel, aams):aari, file: classes.dex
jadx.core.utils.exceptions.JadxRuntimeException: Can't remove SSA var: r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel, still in use, count: 2, list:
  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) from 0x003f: IF  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) == (null com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel)  -> B:26:0x0057 A[HIDDEN]
  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) from 0x0043: PHI (r7v23 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel) = 
  (r7v22 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel)
  (r7v24 com.google.android.libraries.youtube.innertube.model.media.FormatStreamModel)
 binds: [B:18:0x0042, B:16:0x003f] A[DONT_GENERATE, DONT_INLINE]
	at jadx.core.utils.InsnRemover.removeSsaVar(InsnRemover.java:152)
	at jadx.core.utils.InsnRemover.unbindResult(InsnRemover.java:117)
	at jadx.core.dex.visitors.regions.TernaryMod.makeTernaryInsn(TernaryMod.java:114)
	at jadx.core.dex.visitors.regions.TernaryMod.processRegion(TernaryMod.java:62)
	at jadx.core.dex.visitors.regions.TernaryMod.enterRegion(TernaryMod.java:45)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:67)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverse(DepthRegionTraversal.java:19)
	at jadx.core.dex.visitors.regions.TernaryMod.process(TernaryMod.java:35)
	at jadx.core.dex.visitors.regions.IfRegionVisitor.process(IfRegionVisitor.java:33)
	at jadx.core.dex.visitors.regions.IfRegionVisitor.visit(IfRegionVisitor.java:29)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:26)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:72)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:107)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:375)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:299)
	at jadx.api.JavaClass.load(JavaClass.java:127)
	at jadx.api.JavaClass.getMethods(JavaClass.java:308)
	at jadx.gui.utils.JNodeCache.removeWholeClass(JNodeCache.java:53)
	at jadx.gui.treemodel.JClass.unload(JClass.java:88)
	at jadx.gui.ui.dialog.RenameDialog.refreshClasses(RenameDialog.java:198)
	at jadx.gui.ui.dialog.RenameDialog.lambda$refreshState$4(RenameDialog.java:171)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

**Comment by NebelNidas** [comment] 2023-04-21 08:31
Btw, I've been keeping the code from my initial PR up-to-date with latest upstream (pre-`jadx-next`-merge), if you need something to compare against: https://github.com/NebelNidas/jadx/tree/upstream-with-mappingio-import

**Comment by skylot** [comment] 2023-04-22 10:55
> Nice, this means the plugin API is more or less stable now, right?

Right. I will focus on extending API (mostly for gui) and will try to keep current one unchanged.

> If he does, we can simply use the FabricMC maven, if not, we can fork it, of course :)

Great :+1:

> you seem to have introduced another issue

Thanks! I changed a lot of code related to renames, like package renames, deobfuscator split and changes to simplify api for scripts, so this was expected :rofl:
Will try to resolve that issue. Also, next time, please open new issue for new regressions :slightly_smiling_face:

**Comment by NebelNidas** [comment] 2023-06-02 08:31
I did a git bisect, and it turns out the bad commit is d4927db5. All versions before worked fine

**Comment by NebelNidas** [comment] 2023-06-02 19:14
After some investigation, this is what I found out. After you've performed a rename, the following happens when right-clicking on a class name:
- `jadx.gui.ui.codearea.RenameAction#isActionEnabled` returns `false`, which is because `node` is null. That is because
- the `JNode` instance passed from `jadx.gui.ui.codearea.JNodeAction#changeNode` is `null`. That is because
- the `JNode` instance passed from `jadx.gui.ui.codearea.JNodePopupListener#updateNode` is `null`. That is because
- the `JNode` instance passed from `jadx.gui.ui.codearea.JNodePopupListener#popupMenuWillBecomeVisible` is `null`. That is because
- `jadx.gui.ui.codearea.CodeArea#getNodeUnderMouse` is `null`. That is because
- `jadx.gui.ui.codearea.CodeArea#getJNodeAtOffset` is `null`. That is because
- `jadx.gui.ui.codearea.CodeArea#getJavaNodeAtOffset` is `null`. That is because
- `jadx.api.JadxDecompiler#getJavaNodeAtPosition` is `null`. That is because
- jadx.api.metadata.impl.CodeMetadataStorage#getAt` is `null`. That is because
- `position` isn't a valid key for the `navMap`:
![image](https://github.com/skylot/jadx/assets/48808497/f6c71965-121d-4a25-9c52-b70f791845b8)

Before the rename, `position` does point to a valid entry. After the rename, `position` is incremented by one (I guess because of the added `renamed from: ...` comment?), but entries in the `navMap` are shifted by three for whatever reason, leading to this issue. I hope this digestion makes it easier for you to find the culprit.

**Comment by skylot** [comment] 2023-06-02 21:06
@NebelNidas thanks a lot :+1:
Actually here two issues:
- If code have first empty line it got removed, this cause code shift and annotations positions became incorrect and rename not working. This occurs only for default (empty) package, because `package` statements omitted.
- Renaming a class in default package resets assigned `defpackage` alias, so package became empty and cause first issue

 I commit a fix for the first issue. Second looks harder, I will try to fix it tomorrow 

P.S. In most cases bad commit found by bisecting not very helpful for me, so please don't waste your time on bisect :slightly_smiling_face:

**Comment by NebelNidas** [comment] 2023-06-03 07:05
Thank you for the explanation and the quick fix! :)
Since `jadx-next` is merged into master now, I'm going to create separate issues for the remaining problems. Feel free to close this one once you've found a solution for the second issue you mentioned.

**Comment by skylot** [comment] 2023-06-03 14:04
Second issue fixed, so package will not reset on class rename.

**Closed by skylot** 2023-06-03 14:04 UTC
Labels: bug, deobfuscation
