### ISSUE TITLE
[gui] Smali compilation

### ISSUE THREAD

**Issue by wuyo-bit** [skylot/jadx#2303] opened 2024-10-12 10:48 UTC
### Issue details

Jadx version : 1.4.7.276-e73612b4
Java version : 17.0.10
Java VM      : Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
Platform     : Windows 10 (10.0 amd64)
Max heap size: 5516 MB

java.lang.InternalError: Unable to bind C:\Users\24288\Desktop\此电脑.lnk to parent
	at java.desktop/sun.awt.shell.Win32ShellFolder2$4.call(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$4.call(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Unknown Source)
	at java.desktop/sun.awt.shell.ShellFolder.invoke(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2.getIShellFolder(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$16.call(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$16.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Jadx version

1.4.7.276-e73612b4

### Java version

17.0.10

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment] 2024-10-12 11:55
Duplicate of #1930 

Please note that you are using an outdated version of Jadx. Version [1.5.0](https://github.com/skylot/jadx/releases/tag/v1.5.0) has been released about 6 months ago.

**Closed by jpstotz** 2024-10-12 11:55 UTC
Labels: bug, GUI

**Comment by skylot** [comment] 2024-10-12 11:59
@wuyo-bit as a workaround, you can also try to enable `Use alternative file dialog` at `Preferences -> Other` options.
