### ISSUE TITLE
[GUI]Incomplete search reference && smali shows more spaces

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1357] opened 2022-01-25 11:03 UTC
Version:Latest beta version
win10
java8

apk link:https://drive.google.com/file/d/1LxQT_HBN92mIWIUpHWxKPKoEqzZsecEG/view?usp=sharing

1. Bug1:Incomplete search reference

Java, subclasses follow certain rules to inherit member variables and methods from the parent class; however, jadx's lookup references do not seem to support searching for member variables and methods inherited by subclasses;

class:`oicq.wlogin_sdk.b.ac`
method:`public ac()`

![jadx](https://user-images.githubusercontent.com/42903751/150963768-a14ca2d5-2fb4-48a9-9a0e-c5c52be46221.png)
![jadx2](https://user-images.githubusercontent.com/42903751/150963803-04a6e9f2-8fc9-4de6-89d0-30604dcc59c5.png)

In Jeb:
![jeb](https://user-images.githubusercontent.com/42903751/150963898-055c8c3e-fae7-4908-a8a7-728de7204df5.png)

2. Bug2:smali shows more spaces

![jadx-smali](https://user-images.githubusercontent.com/42903751/150964205-dcb8bd16-265d-4e8a-be8f-62c82b350129.png)

**Comment by skylot** [comment] 2022-01-25 12:04
@xmhwws thanks for report!
I commit a fix for usage, please check.
About smali issue: I have no idea how that happen, and I can't reproduce it :(

**Comment by xmhwws** [comment] 2022-01-25 14:01
> @xmhwws thanks for report! I commit a fix for usage, please check. About smali issue: I have no idea how that happen, and I can't reproduce it :(

Bug1.Look up the reference, I tested it, my example has no bugs, but I do not have examples of subclasses overriding parent methods, still need you to test;

Bug2.When the editor font is OPPOSans-M, smali display will be abnormal; change the font to Consolas, normal display;
![2022-01-25_21-54-12](https://user-images.githubusercontent.com/42903751/150990142-5b717dc9-a593-48e3-be48-7515384b8561.png)

Link to windows font package:http://static01.coloros.com/www/public/img/topic7/font-opposans.zip

My jadx configuration:{
  "flattenPackage": false,
  "checkForUpdates": false,
  "fontStr": "OPPOSans M/plain/13",
  "smaliFontStr": "",
  "editorThemePath": "/org/fife/ui/rsyntaxtextarea/themes/default.xml",
  "lafTheme": "FlatLaf Light",
  "langLocale": {
    "locale": "zh_CN"
  },
  "autoStartJobs": false,
  "excludedPackages": "android androidx",
  "autoSaveProject": false,
  "showHeapUsageBar": true,
  "alwaysSelectOpened": false,
  "codeAreaLineWrap": true,
  "srhResourceSkipSize": 3,
  "srhResourceFileExt": ".xml|.html|.js|.json|.txt",
  "keepCommonDialogOpen": false,
  "smaliAreaShowBytecode": false,
  "lineNumbersMode": "AUTO",
  "mainWindowVerticalSplitterLoc": 300,
  "debuggerStackFrameSplitterLoc": 300,
  "debuggerVarTreeSplitterLoc": 700,
  "adbDialogPath": "",
  "adbDialogHost": "localhost",
  "adbDialogPort": "5037",
  "treeWidth": 537,
  "settingsVersion": 15,
  "skipResources": false,
  "skipSources": false,
  "exportAsGradleProject": false,
  "threadsCount": 5,
  "showInconsistentCode": true,
  "useImports": true,
  "debugInfo": true,
  "addDebugLines": false,
  "inlineAnonymousClasses": true,
  "inlineMethods": false,
  "replaceConsts": true,
  "escapeUnicode": false,
  "respectBytecodeAccessModifiers": true,
  "deobfuscationOn": true,
  "deobfuscationMinLength": 3,
  "deobfuscationMaxLength": 64,
  "deobfuscationForceSave": false,
  "deobfuscationUseSourceNameAsAlias": true,
  "deobfuscationParseKotlinMetadata": true,
  "useKotlinMethodsForVarNames": "APPLY",
  "renameFlags": [],
  "fsCaseSensitive": false,
  "cfgOutput": false,
  "rawCfgOutput": false,
  "fallbackMode": false,
  "useDx": true,
  "commentsLevel": "INFO"
}

**Comment by skylot** [comment] 2022-01-25 19:00
@xmhwws looks like this is not a space as a character but rendering issue in [RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea), so only I can do is to suggest using another font :neutral_face:

Anyway, I think I fix everything I can in this issue, so I will close it.
If any new cases appear, please open a new issue.

**Closed by skylot** 2022-01-25 19:00 UTC
Labels: bug, Core
