### ISSUE TITLE
Closing jadx main window only hides it

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#639] opened 2019-04-26 08:31 UTC
If you close the jadx main windows while decompilation is in progress the main windows is just hidden but the decompilation continues which occupies CPU and RAM. 

This problem was introduced by PR #543 by changing the `DefaultCloseOperation` in MainWindow.java from `WindowConstants.EXIT_ON_CLOSE` to `WindowConstants.DO_NOTHING_ON_CLOSE`.

For some tests I changed it back to `EXIT_ON_CLOSE` and did not notice any problems - but I am not an expert of the new project system. @asashour Can you please check if going back to `EXIT_ON_CLOSE` would be possible without problems?

**Comment by asashour** [comment] 2019-04-26 08:55
I would say, the root cause is that `cancelBackgroundJobs()` doesn't stop the decompilation.

However, there is no harm if we call `System.exit()` as in the proposed PR.

**Comment by skylot** [comment] 2019-04-29 12:56
I have merged that PR, but it is a workaround and root cause must be fixed.
`EXIT_ON_CLOSE` must be used to close last window and method `cancelBackgroundJobs()` must be fixed because it is used in other cases like canceling decompilation and opening another file if previous still decompiling.

**Comment by asashour** [comment] 2019-04-29 13:20
But `EXIT_ON_CLOSE` should not be used, because otherwise we will not ask the user to save the project before exiting.

I am definitely with fixing `cancelBackgroundJobs()`

**Comment by jpstotz** [comment] 2019-04-29 14:49
@skylot According to [this article on Stackoverflow.com](https://stackoverflow.com/questions/8597140/system-exit0-vs-jframe-exit-on-close) `EXIT_ON_CLOSE` is equivalent to calling `System.exit(0);`

**Comment by skylot** [comment] 2019-04-29 15:01
@jpstotz yeah, I already checked sources. But I don't like `System.exit(0)` in code. Anyway, it is acceptable.

Also, I thought that as soon as we closing window from callback it is possible to stop the propagation of closing event, but it is not true. So @asashour I am sorry for the incorrect statement :(

In result, I think `System.exit(0)` and `DO_NOTHING_ON_CLOSE` is ok.

**Closed** 2022-03-19 09:57 UTC
Labels: bug, GUI
