### ISSUE TITLE
[gui] another gradle issue

### ISSUE THREAD

**Issue by jmxamongusmodder** [skylot/jadx#2084] opened 2024-01-19 23:03 UTC
### Issue details

I am so mad.
i have an androidmanifest.xml but jadx here is saying it cant find it EVEN THO I OPENED THE ENTIRE PROJECT!
THIS IS SO STUPID WHAT THE FU** IS WRONG WITH IT!!

### Jadx version

unstable build

### Java version

bro i dont know

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment] 2024-01-20 17:20
Duplicate of #2078. 
As mentioned in this issue Gradle export is designed for APK only projects at the moment so only in this case it is supposed to work it Jadx-Gui is enhances to support more scenarios. Feel free to help us extend the Gradle export functionality to general projects.

And IMHO you should really try to include a bit more friendliness in your issue description...

**Closed by jpstotz** 2024-01-20 17:20 UTC
Labels: bug, GUI
