### ISSUE TITLE
[gui] SAVE AS GRADLE DOESNT WORK

### ISSUE THREAD

**Issue by jmxamongusmodder** [skylot/jadx#2078] opened 2024-01-09 01:12 UTC
### Issue details

BRO STUPID SAVE AS GRADLE DOESNT WORK

### Jadx version

the latest one

### Java version

i forgor

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment] 2024-01-09 10:01
Please provide more details on what problem you face and what app/file you have loaded in Jadx.

**Comment by piccinnigius** [comment] 2024-01-17 11:52
same here

**Comment by jpstotz** [comment] 2024-01-17 13:34
@piccinnigius Please describe in detail what does not work. What have you loaded into Jadx-GUI? And when you execute export as Gradle what do you get?

**Comment by piccinnigius** [comment] 2024-01-17 14:51
Hi, I’ve loaded an apk as smali code.
When I click export as gradle project, select folder, ok button and the
window closes without error but in the selected export folder there is
nothing

Il giorno mer 17 gen 2024 alle 14:34 Jan S. ***@***.***> ha
scritto:

**Comment by jpstotz** [comment] 2024-01-17 15:34
As far as I remember the Export as Gradle project is mainly designed to export a loaded APK file as Grade project. Not sure if other input formats are also supported. 

May be we have to disable this feature if the loaded project misses the required files.

**Comment by piccinnigius** [comment] 2024-01-17 15:36
Yes, my fix was to include also the apk in the project aside the smali
files decompiled from odex source

**Comment by skylot** [comment] 2024-01-17 18:57
@jpstotz I think `Export as Gradle` should handle any input, because this is the only way to open jadx results in other IDEs.
So we should get rid of throwing exceptions and use some defaults to fill missing metadata. And, maybe, if inputs don't contain AndroidManifest.xml and resources, we can export as plain java project.
Such changes needed a bit of refactoring, also it is worth adding support for AAR libs as requested in #2044.
Looks like this issue is duplicate of earlier #1918, so I will close it.

**Closed by skylot** 2024-01-17 18:57 UTC
Labels: bug, GUI, waiting for reply
