### ISSUE TITLE
characters garbled

### ISSUE THREAD

**Issue by chaoliu1024** [skylot/jadx#440] opened 2019-02-12 07:13 UTC
Characters in toolbar and dialog are garbled where using mac open it. All characters show like "????"
jadx version is 0.8.0
<img width="1439" alt="jadx" src="https://user-images.githubusercontent.com/9319628/52618147-f9300c00-2ed8-11e9-8645-ad0a59afd66e.png">

**Comment by jpstotz** [comment] 2019-02-12 09:01
Duplicate of #363 

This issue is already fixed in the latest unstable version.

**Comment by skylot** [comment] 2019-02-12 09:09
@jpstotz looks like I need to release a new version. Do you think that we fix all issues after enabling multi-threaded decompilation? Or maybe you know other serious issues that I still not fix?

**Comment by jpstotz** [comment] 2019-02-12 09:19
I have not encountered severe issues the last times I used Jadx. Therefore from my point of view a new release would be a good idea.

**Comment by skylot** [comment] 2019-02-12 09:42
@jpstotz release done, version 0.9.0 :+1:

**Closed by skylot** 2019-02-12 09:42 UTC
