### ISSUE TITLE
[feature] Support for renaming classes, methods and fields

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#791] opened 2019-12-10 13:35 UTC
Hello.

I added a Rename popup menu item that allows the user to rename classes, methods and fields.
It is useful for obfuscated code, it makes it much easier to read.
The implementation is very basic and perhaps not optimal, but it works.
I pushed it to https://github.com/S-trace/jadx/tree/rename
Could you please review it and allow me to open a pull request?

Thanks.

**Comment by skylot** [comment] 2019-12-10 18:34
@S-trace good implementation, thanks!
Although your approach is a little different from what I describe in #524 [in this comment](https://github.com/skylot/jadx/issues/524#issuecomment-477120938), I think it is a good start, so we can improve this later. Please, open a PR :)
Also, this implementation will close #88 and this is great!

**Comment by S-trace** [comment] 2019-12-10 18:45
I'm working right now for a more advanced implementation of this feature, which will not reload whole file, but now I'm have a problem with renaming inner classes renaming and with renaming classes in methods parameters (regular classes renaming, methods renaming and fields renaming works fine).

I hope i can finish this update and push another commit to the same branch.
But it's possible to merge current implementation now and wait for updated implementation (no feature is worse than slow but working feature).

Thank you.

**Comment by S-trace** [comment] 2019-12-11 07:46
I pushed updated rename implementation to https://github.com/S-trace/jadx/tree/rename2
Could you please review and test it?

It still have a problem with renaming classes from import statements and method arguments list, but all other usecases seems working fine.
I'm not too familiar with jadx architecture, so any tips and hints are welcome.

Thank you!

**Comment by S-trace** [comment] 2019-12-11 15:35
About performance:
Tried to rename 2 classes in the project containing 6622 classes, 1249 of them excluded. classes.dex size is 7665080 bytes.
Rename was performed twice: first time in clean project with only renaming class open (best case, only renamed class will be redecompiled), second time after performing "Find usages" for the class (worst case, all classes referring to renamed class will be redecompiled).

Results:

Class1: 217725 bytes, 5079 lines
Clean state:
refreshState() took 1692 ms to update state, 0 classes to be upgraded in background (1768 ms total)

After "Find usages"
refreshState() took 1801 ms to update state, 121 classes to be upgraded in background (1875 ms total)
INFO  - Memory usage: Before refresh: heap: 238MB, allocated: 795MB, free: 556MB, total free: 3857MB, max: 4096MB
INFO  - Memory usage: After refresh: heap: 239MB, allocated: 795MB, free: 555MB, total free: 3856MB, max: 4096MB, refresh took 989 ms

Class2: 13305 bytes, 539 lines:
Clean state:
INFO  - refreshState() took 382 ms to update state, 0 classes to be upgraded in background (464 ms total)

After "Find usages":
INFO  - refreshState() took 227 ms to update state, 26 classes to be upgraded in background (310 ms total)
INFO  - Memory usage: Before refresh: heap: 234MB, allocated: 782MB, free: 547MB, total free: 3861MB, max: 4096MB
INFO  - Memory usage: After refresh: heap: 236MB, allocated: 782MB, free: 545MB, total free: 3859MB, max: 4096MB, refresh took 974 ms

So, rename still works a bit slow.
@skylot About your comment in #524: Partial decompilation may improve rename performance, I think. Is it hard to implement this?

Thank you.

**Comment by skylot** [comment] 2019-12-11 17:51
@S-trace I checked your updated implementation and it is great!
And working well and fast enough so I think you don't need to worry about performance :+1: 
The only thing I found is that renamed classes sometimes not reindexed so text search can't find a new name.
About partial decompilation: you already did it! :) I mean you decompile only needed classes instead all of them. And leveling minimal decompilation unit to the method will need lots of efforts and I don't think that such change will greatly increase rename time.

**Comment by S-trace** [comment] 2019-12-12 05:38
Thank you.
I tried to implement partial reindexing, but it's not ready yet.

**Comment by S-trace** [comment] 2019-12-12 18:44
Found and fixed critical bug with static fields initializers, comments source file name information - they was lost after class refresh.

But there is still a werid bug/feature: for String getters for private static final String fields string content inlines to getter's body after rename.
@skylot could you please check this?

Thank you.

**Comment by skylot** [comment] 2019-12-13 17:32
@S-trace I checked latest update to `rename2` branch. Looks like your approach to refresh code in `ClassNode` is not the best way to do that, better way is to fix class state processing and instead `UNLOADED` state go to initial `NOT_LOADED` this will allow reloading class without problems and lots of additional code. I think I can push such change quite soon.

About index: sure it is possible to just replace info for refreshed classes. Also, I think I will reimplement whole code indexing to allow regexp search. This change will remove the need to actually scan code before the search, so this will resolve the issue with reindexing.

About "inline": this is funny, but actually you see that feature "Replace constants" just stop working. Maybe because constant refers to an invalid 'old' field. Mapping to/from constants stored in `ConstStorage` and must be also replaced on renaming. And looks like this fix will be not easy (

**Comment by S-trace** [comment] 2019-12-13 17:44
@skylot Thank you for explaining this bug.

But there is still a question: may we turn this bug to feature, lile "Deep inline constants" option?
I tried to work with obfuscated code after this deep constants inlining - reading code after deep inlining really becomes much more easy.

**Comment by skylot** [comment] 2019-12-13 17:49
@S-trace you can just disable "Replace constants" in jadx-gui preferences or use `--no-replace-consts` in jadx-cli. Hope is that you want :)

**Comment by skylot** [comment] 2019-12-13 19:38
@S-trace I added method `reloadCode()` to `ClassNode` which simplify code reloading and regeneration. Checks commit 1c6e51f. Hope it helps.

**Comment by S-trace** [comment] 2020-01-03 03:28
Pushed updated rename implementation to https://github.com/S-trace/jadx/tree/rename3
It still have minor issue (access flags sometimes got changed, even when "Respect bytecode access modifiers" is enabled).

I'm not sure about commits https://github.com/S-trace/jadx/commit/6d4caca6cc46019ce66469171b918aa16f62b59e and https://github.com/S-trace/jadx/commit/610f531653fcfa7042de2f53c69d5a102ed91102 - maybe it may be better solution for those problems?

Also, there is a workaround in commits https://github.com/S-trace/jadx/commit/d346ed0570dcaea21d018877273e7fe6f640cc98 and https://github.com/S-trace/jadx/commit/17cbb3eab0a725b7c9946ceda54dbeb9c639b29d - maybe, this issue should be resolved more elegant way?

@skylot could you please review and test this version? 
It's looks good enough for me, i checked it on 2 APK files, and refreshed classes looks fine for me (code before/after refreshing classes isn't exactly same, but differs in errors comments, auto-generated variable names and (as i mentioned above) sometimes in access modifiers with appropriate comments).

Thank you, and happy New Year!

**Comment by skylot** [comment] 2020-01-03 19:00
@S-trace thank you for great work!
I agree, some changes are very hacky and looks like a problem is not complete class reloading.
My vision is to make full reload of class without small tweaks so visitors code in `jadx-core` must stay unchanged and decompiled code also must not change.
I made another try for correct class reloading thanks to your changes, please check `rename` branch and 0c4b807caa7fa110dcfc06809d50f8ce519cfbbf commit. Also, I want to make some tests for reloading, so if you find any issue please describe how to reproduce it.

**Comment by S-trace** [comment] 2020-01-03 21:29
@skylot 
I checked commit https://github.com/skylot/jadx/commit/0c4b807caa7fa110dcfc06809d50f8ce519cfbbf and found following issues (comparing https://github.com/skylot/jadx/commit/1eca2b6cb0163e696c3f524bdba9c22b79dc8fe7 and https://github.com/skylot/jadx/commit/0c4b807caa7fa110dcfc06809d50f8ce519cfbbf outputs after refreshing every class in apk):

1. static final initializers (for example, resources IDs in android.support.coreutils.R) is lost on classes refresh - was fixed in https://github.com/skylot/jadx/commit/f90fc1d5ec8413cb9a4bcca03930e6c721fe4161
2. "Replace constants" stopped working on class refresh (for example, in android.support.customtabs.CustomTabsSessionToken class CustomTabsSessionToken.TAG field reference becomes "CustomTabsSessionToken" string) - was fixed in https://github.com/skylot/jadx/commit/15953f832f8863cdd141e04f81c872448be9701b
3. In inner classes constructors (for example, in alice.tuprolog.Agent.AgentThread class) assignment to parent's instance synthetic field (Agent.this = this$0;) appears on class refresh  - was fixed in https://github.com/skylot/jadx/commit/6d4caca6cc46019ce66469171b918aa16f62b59e. Also, this could lead to /* JADX INFO: super call moved to the top of the method (can break code semantics) */ comment (for example, in android.support.design.widget.FloatingActionButtonImpl.ResetElevationAnimation constructor).
4. Method's signature "throws" part is lost on class refresh (for example, in android.support.customtabs.IPostMessageService.onTransact(int code, Parcel data, Parcel reply, int flags) "throws RemoteException" part is lost) - don't know exactly when this was fixed
5. Annotations (for example, in android.support.customtabs.CustomTabsService @Retention(RetentionPolicy.SOURCE) annotation is lost) - was fixed in https://github.com/skylot/jadx/commit/f90fc1d5ec8413cb9a4bcca03930e6c721fe4161
6. Comments is lost on class refresh (for example, on android.support.design.widget.AppBarLayout.Behavior.canDragView(AppBarLayout view) comment  /* access modifiers changed from: package-private */ is lost) - was fixed in https://github.com/skylot/jadx/commit/f90fc1d5ec8413cb9a4bcca03930e6c721fe4161
7. 0/false/null initializers for inal fields initialized in constructor appeared on class refresh (for example, null initializer for static final InverseUCA INVERSE_UCA_ in class com.ibm.icu.text.CollationParsedRuleBuilder) - was fixed in https://github.com/skylot/jadx/commit/df520a11341e0fa3a08ad339d44ac07baade46b5
8. Multiple decompilation failures in class com.ibm.icu.text.CollationParsedRuleBuilder (for example, InverseUCA inner class constructor wasn't decompiled with following stacktrace:
```
    /*  JADX ERROR: NullPointerException in pass: ConstInlineVisitor
        java.lang.NullPointerException
               at jadx.core.dex.visitors.ConstInlineVisitor.process(ConstInlineVisitor.java:50)
               at jadx.core.dex.visitors.ConstInlineVisitor.visit(ConstInlineVisitor.java:45)
```
And there is following stacktrace in CollationParsedRuleBuilder(String rules)  constructor:
```
    /*  JADX ERROR: NullPointerException in pass: InitCodeVariables
        java.lang.NullPointerException
               at jadx.core.dex.visitors.InitCodeVariables.initCodeVar(InitCodeVariables.java:56)
               at jadx.core.dex.visitors.InitCodeVariables.initCodeVars(InitCodeVariables.java:45)
               at jadx.core.dex.visitors.InitCodeVariables.visit(InitCodeVariables.java:32)
```
Whole sources/com/ibm/icu/text/CollationParsedRuleBuilder.java is very corrupted, with many stacktraces and fallback dumped methods.

APK used for testing:
https://drive.google.com/open?id=1KXq2uimU-nrEgdKKv7moG7MBJw3ARmvbwOX31KKp2Qg
(file too large to attach it here, so i google drived it).

For refreshing every class in APK i replaced https://github.com/skylot/jadx/blob/rename/jadx-gui/src/main/java/jadx/gui/ui/RenameDialog.java#L218 line to:
```
Set<JavaClass> updatedClasses = new HashSet<>(mainWindow.getWrapper().getClasses());
```

I'd used following sequence: 
1. Load APK
2. Use "Save all" to get original (just decompiled) sources
3. Rename any class to same name (this triggers refresh for all classes) 
4. Use "Save all" again to get refreshed sources
5. Compare directories from step 2 and step 4 (this could visualize any class refresh errors).

Of course, refreshed sources from different jadx builds could also be compared to check is one build better or worse than another.

**Comment by skylot** [comment] 2020-01-05 19:30
@S-trace thanks for the detailed issues description. I made some fixes in `rename` branch.
But unfortunately, I can't download your sample APK due to permission restrictions, please open access to that file or post another link.
Anyway, I will continue to work on these issues.
And again thank you for your help 👍

**Comment by S-trace** [comment] 2020-01-05 19:32
@skylot Sorry, somehow i posted a wrong link - updated the comment above for right link to the APK.

**Comment by S-trace** [comment] 2020-01-05 20:09
@skylot - looking on your changes:
https://github.com/skylot/jadx/commit/9dbffef14044c78461f29cbee09bf1521eecbab9#diff-de1198551bfe73cbe51d902850ee12cdR65 - is this really necessary?
If the constant already got duplicates - it will have duplicates even after class reload, won't it?
But removing this constant from duplicates could break replace constants (just imagine a class with public final int TEST_CONSTANT = 1 - after reloading this class each "(int) 1" litheral will be replaced to "TEST_CONSTANT" and trivial increments will become werid expressions (int y = x + 1 will become int y = x + TestClass.TEST_CONSTANT).

**Comment by skylot** [comment] 2020-01-05 20:38
@S-trace you are right, thanks! This line is not needed :)

**Comment by S-trace** [comment] 2020-01-16 21:29
@skylot 
I pushed some fixes to https://github.com/S-trace/jadx/tree/rename4 - please review it and merge to your rename branch

**Comment by skylot** [comment] 2020-01-17 08:08
@S-trace all changes look good. Thanks! I updated `rename` branch.
Is there are any issues left that needs to be fixed?
I only notice access modifiers changes, but it looks minor to me.
So, I think we can merge `rename` into master :)

**Comment by S-trace** [comment] 2020-01-17 09:50
@skylot Threre are still many decompilation failures in this version (comparing initial decompilation results and results after refreshing each class):

sources/alice/tuprolog/Number.java:
```
/*  JADX ERROR: ConcurrentModificationException
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:316)
        at jadx.core.ProcessClass.process(ProcessClass.java:36)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at jadx.core.ProcessClass.generateCode(ProcessClass.java:59)
        at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:309)
        at jadx.core.dex.nodes.ClassNode.reloadCode(ClassNode.java:285)
    */
/*  JADX ERROR: JadxRuntimeException in pass: ClassModifier
    jadx.core.utils.exceptions.JadxRuntimeException: Method args not loaded: alice.tuprolog.Number.<init>():void, class status: PROCESS_STARTED
        at jadx.core.dex.nodes.MethodNode.getArgRegs(MethodNode.java:287)
        at jadx.core.dex.visitors.ClassModifier.removeEmptyMethods(ClassModifier.java:312)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at jadx.core.dex.visitors.ClassModifier.visit(ClassModifier.java:59)
    */
/*  JADX ERROR: NullPointerException in pass: ExtractFieldInit
    java.lang.NullPointerException
        at jadx.core.utils.BlockUtils.isAllBlocksEmpty(BlockUtils.java:586)
        at jadx.core.dex.visitors.ExtractFieldInit.getConstructorsList(ExtractFieldInit.java:245)
        at jadx.core.dex.visitors.ExtractFieldInit.moveCommonFieldsInit(ExtractFieldInit.java:126)
        at jadx.core.dex.visitors.ExtractFieldInit.visit(ExtractFieldInit.java:46)
    */
    /*  JADX ERROR: Method load error
        jadx.core.utils.exceptions.DecodeException: Load method exception: null in method: alice.tuprolog.Number.<init>():null, dex: classes.dex
                at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:151)
                at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:148)
                at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:318)
                at jadx.core.ProcessClass.process(ProcessClass.java:36)
                at java.util.ArrayList.forEach(ArrayList.java:1257)
                at jadx.core.ProcessClass.generateCode(ProcessClass.java:59)
                at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:309)
                at jadx.core.dex.nodes.ClassNode.reloadCode(ClassNode.java:285)
        Caused by: java.lang.NullPointerException
                at jadx.core.dex.nodes.MethodNode.initArguments(MethodNode.java:262)
                at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:125)
                ... 7 more
        */
/*
Method generation error in method: alice.tuprolog.Number.<init>():void, dex: classes.dex
    jadx.core.utils.exceptions.JadxRuntimeException: Method args not loaded: alice.tuprolog.Number.<init>():void, class status: PROCESS_COMPLETE
        at jadx.core.dex.nodes.MethodNode.getArgRegs(MethodNode.java:287)
        at jadx.core.codegen.MethodGen.addDefinition(MethodGen.java:116)
        at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:317)
        at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:275)
        at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$2(ClassGen.java:244)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at jadx.core.codegen.ClassGen.addInnerClsAndMethods(ClassGen.java:240)
        at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:231)
        at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:115)
        at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:81)
        at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:45)
        at jadx.core.codegen.CodeGen.generateJavaCode(CodeGen.java:34)
        at jadx.core.codegen.CodeGen.generate(CodeGen.java:22)
        at jadx.core.ProcessClass.generateCode(ProcessClass.java:61)
        at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:309)
        at jadx.core.dex.nodes.ClassNode.reloadCode(ClassNode.java:285)
*/
```
sources/android/support/design/widget/CoordinatorLayout.java:
```
null initializers appeared for fields:
static final Comparator<View> TOP_SORTED_CHILDREN_COMPARATOR; 
static final String WIDGET_PACKAGE_NAME;

Initializes was replaced to null and moved to class constructor (obliviosly worng for final fields):
static final Class<?>[] CONSTRUCTOR_PARAMS = {Context.class, AttributeSet.class};
private static final Pools.Pool<Rect> sRectPool = new Pools.SynchronizedPool(12);

Synthetic methods appeared:
protected /* bridge */ /* synthetic */ ViewGroup.LayoutParams generateDefaultLayoutParams()
public /* bridge */ /* synthetic */ ViewGroup.LayoutParams generateLayoutParams(AttributeSet attributeSet) 
protected /* bridge */ /* synthetic */ ViewGroup.LayoutParams generateLayoutParams(ViewGroup.LayoutParams layoutParams)

In OnPreDrawListener() call "this" parameter was appeared:
this.mOnPreDrawListener = new OnPreDrawListener(); 

Following ititialzers was lost:
        public int anchorGravity = 0;
        public int dodgeInsetEdges = 0;
        public int gravity = 0;
        public int insetEdge = 0;
        public int keyline = -1;
        int mAnchorId = -1;
```

sources/alice/tuprolog/Prolog.java:
```
/*  JADX ERROR: NullPointerException in pass: ClassModifier
    java.lang.NullPointerException
        at jadx.core.utils.BlockUtils.collectAllInsns(BlockUtils.java:596)
        at jadx.core.dex.visitors.ClassModifier.removeBridgeMethod(ClassModifier.java:220)
        at jadx.core.dex.visitors.ClassModifier.removeSyntheticMethods(ClassModifier.java:151)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at jadx.core.dex.visitors.ClassModifier.visit(ClassModifier.java:58)
    */
    /*  JADX ERROR: NullPointerException in pass: BlockExceptionHandler
        java.lang.NullPointerException
        */
UnsupportedOperationException("Method not decompiled: alice.tuprolog.Prolog.<init>(boolean, boolean):void");
```

**Comment by skylot** [comment] 2020-01-17 13:58
@S-trace looks like these are multi-threading issues, I don't see them if processing threads count set to 1. The cause is simple: we can't deep unload class then parallel thread trying to get info about that class. To check that I move classes unload before multi-threaded `refresh` execution, for me it resolve all mentioned issues, check 72b449e6c8fb14a3e81d465f5cd427b16a65df8c commit in `rename-tmp` branch.

**Comment by S-trace** [comment] 2020-01-17 20:16
@skylot 
I checked 72b449e commit in rename-tmp branch - refreshed code looks much better with it (no new stacktraces appeared in the code after full refresh in 12 threads).
But there are several regressions:

1. static final fields initializers was lost (static final int TRANSACTION_* in android/support/v4/media/session/IMediaControllerCallback.java for example).
2. Access modifiers modified on initial decompilation was reset to original (void count(int read) method in org/apache/commons/compress/archivers/ArchiveInputStream.java for example)
.
3. 'reason: invalid class name' part was lost from 'renamed from: ' comments (org/apache/commons/compress/compressors/lz4/BlockLZ4CompressorOutputStream.java for example).
4. 'throws ' part of methods signatures was lost (public void onMetadataChanged(MediaMetadataCompat metadata) method in android/support/v4/media/session/IMediaControllerCallback.java for example).
5. There is something werid with commented literal values of constants for switch cases - these comments appeared in many places (why does they not appeared on initial decompilation?), but  one comment have disappeared in android/support/media/ExifInterface.java case IntervalSize.MIN_BINARY_EXPONENT /*-50*/ where it was before.
6. 'compiled from' comments was lost (in com/google/gson/internal/C$Gson$Types.java for example)
7. com/ibm/icu/text/StringSearch.java file appeared (and it looks as correctly decompiled) - so, it seems this file was lost on initial decompilation.

Thank you!

**Comment by skylot** [comment] 2020-01-20 10:07
@S-trace I checked some regressions you mention and looks like most of them not rename feature related but occur because of not correct processing order. It is already discussed somewhere in issues, so in short: jadx must process classes by dependencies between them, but jadx doesn't have such info before decompilation. So now decompilation results kind of "unstable" and especially if several threads used for processing. I have planned how to fix this, but don't have much time to implement these plans :(

> Maybe commit 4674033 should be reverted after commit 72b449e for better performance?

I think it is ok to leave it thread-safe because ... well, it is safer :)

> I'm have some thoughts for improving usability of renaming ...

Great! A hotkey is a must feature. Others are also nice to have.

**Comment by S-trace** [comment] 2020-03-09 13:55
@skylot 
I tried to merge skylot/master to skylot/rename branch, but have a failed TestAnonymousInline test after this.
Could you please check this?
Thank you.

**Comment by skylot** [comment] 2020-03-09 20:01
@S-trace merged and fixed.
Test failed because of comment with inlined class name which was added in PR #865.

**Comment by yeshen4328** [comment] 2020-05-08 04:43
can I rename fields or classes manually?

**Comment by S-trace** [comment] 2020-07-02 12:30
@yeshen4328 Yes, you can rename classes, methods and fields manually by modifying the deobf map and reloading the file (but my rename implementations allows you to do this a lot faster (except when you are scripting the things).

**Comment by skylot** [comment] 2020-08-03 13:07
I have merged the `rename` branch into master and make use of new usage info, so no need to run full decompilation to collect classes usage. Also, I add incremental indexing. Hope this will be useful.
Anyway, I don't like that current implementation needs enabled deobfuscation. I will try to make rename as an independent visitor and store all user renames in the project file.

**Comment by skylot** [comment] 2020-11-03 19:02
I think we can close this issue. There are lots of fixes in latest master, so any bugs must be reported in new issue.

**Closed by skylot** 2020-11-03 19:02 UTC
Labels: new feature
