### ISSUE TITLE
[gui] Crash on Mac OS 14.5

### ISSUE THREAD

**Issue by dengshiwei** [skylot/jadx#2221] opened 2024-07-23 10:56 UTC
### Issue details

Mac OS 版本14.5 打开会出现崩溃。
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[AWTView keyboardInputSourceChanged:]: unrecognized selector sent to class 0x1442823e0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff80996b89e __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80945c21b objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff809a109f5 -[NSObject(NSObject) doesNotRecognizeSelector:] + 0
	3   CoreFoundation                      0x00007ff8098d9b08 ___forwarding___ + 1379
	4   CoreFoundation                      0x00007ff8098d9518 _CF_forwarding_prep_0 + 120
	5   CoreFoundation                      0x00007ff8098eedf6 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
	6   CoreFoundation                      0x00007ff80997ea6c ___CFXRegistrationPost_block_invoke + 86
	7   CoreFoundation                      0x00007ff80997e9bd _CFXRegistrationPost + 530
	8   CoreFoundation                      0x00007ff8098be749 _CFXNotificationPost + 826
	9   Foundation                          0x00007ff80a7b6d0e -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
	10  AppKit                              0x00007ff80d221c13 __NSSelectedKeyboardInputSourcesChangedNotification + 58
	11  CoreFoundation                      0x00007ff8098eee2e __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 193
	12  CoreFoundation                      0x00007ff80997ea6c ___CFXRegistrationPost_block_invoke + 86
	13  libdispatch.dylib                   0x00007ff809679ac6 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007ff80967adbc _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007ff8096871df _dispatch_main_queue_drain + 984
	16  libdispatch.dylib                   0x00007ff809686df9 _dispatch_main_queue_callback_4CF + 31
	17  CoreFoundation                      0x00007ff80993911a __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x00007ff8098f87c0 __CFRunLoopRun + 2463
	19  CoreFoundation                      0x00007ff8098f7859 CFRunLoopRunSpecific + 557
	20  HIToolbox                           0x00007ff8147eaa09 RunCurrentEventLoopInMode + 292
	21  HIToolbox                           0x00007ff8147ea816 ReceiveNextEventCommon + 665
	22  HIToolbox                           0x00007ff8147ea561 _BlockUntilNextEventMatchingListInModeWithFilter + 66
	23  AppKit                              0x00007ff80cec9c61 _DPSNextEvent + 880
	24  AppKit                              0x00007ff80d7dddc0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1273
	25  libosxapp.dylib                     0x0000000143e996ce -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	26  AppKit                              0x00007ff80cebb075 -[NSApplication run] + 603
	27  libosxapp.dylib                     0x0000000143e99513 +[NSApplicationAWT runAWTLoopWithApp:] + 263
	28  libawt_lwawt.dylib                  0x000000014424aa74 +[AWTStarter starter:headless:] + 496
	29  libosxapp.dylib                     0x0000000143e9b029 +[ThreadUtilities invokeBlockCopy:] + 15
	30  Foundation                          0x00007ff80a82b365 __NSThreadPerformPerform + 178
	31  CoreFoundation                      0x00007ff8098f97d6 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	32  CoreFoundation                      0x00007ff8098f9779 __CFRunLoopDoSource0 + 157
	33  CoreFoundation                      0x00007ff8098f9548 __CFRunLoopDoSources0 + 215
	34  CoreFoundation                      0x00007ff8098f81b8 __CFRunLoopRun + 919
	35  CoreFoundation                      0x00007ff8098f7859 CFRunLoopRunSpecific + 557
	36  libjli.dylib                        0x000000010b9075ac CreateExecutionEnvironment + 398
	37  libjli.dylib                        0x000000010b903817 JLI_Launch + 1315
	38  java                                0x0000000102f712cc main + 364
	39  dyld                                0x0000000203179366 start + 1942
)
libc++abi: terminating due to uncaught exception of type NSException
[1]    46524 abort      /Users/dengshiwei/Desktop/jadx-1.5.0/bin/jadx-gui

Saving session...completed.

[进程已完成]

### Jadx version

1.5.0

### Java version

11.0.13

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by jpstotz** [comment] 2024-07-23 11:18
As Jadx does not contain any native libraries (just Java byte code). Thus Java crashes with native stacktrace are caused by the Java Runtime, not by Jadx. There is nothing we can do to prevent this crash.

Java version 11.0.13 was released in 2021, may be updating it to the latest 11.x version prevents such crashes? Please keep in mind that most Java 11 distributions are already end-of-life. Therefore switching to the latest Java 17 version would be my recommendation.

**Closed** 2024-07-24 06:01 UTC
Labels: bug, GUI
