### ISSUE TITLE
[core] NPE in pass ProcessVariables

### ISSUE THREAD

**Issue by iscle** [skylot/jadx#2382] opened 2024-12-24 22:28 UTC
### Issue details

While decompiling [this version of the Waze app](https://www.apkmirror.com/apk/waze/waze-gps-maps-traffic-alerts-live-navigation/waze-gps-maps-traffic-alerts-live-navigation-5-2-0-3-release/waze-navigation-live-traffic-5-2-0-3-android-apk-download/) jadx threw the following error in the console, which might be related to some issues I have while searching for method calls and variable usages.

```
ERROR - NullPointerException in pass: ProcessVariables in method: go.t.w0(java.lang.Iterable, java.lang.Appendable, java.lang.CharSequence, java.lang.CharSequence, java.lang.CharSequence, int, java.lang.CharSequence, to.l, int, java.lang.Object):java.lang.Appendable, file: classes6.dex
java.lang.NullPointerException: Cannot invoke "jadx.core.dex.instructions.args.SSAVar.getUseList()" because "ssaVar" is null
	at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.processBlock(ProcessVariables.java:96)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:64)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverse(DepthRegionTraversal.java:19)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables.removeUnusedResults(ProcessVariables.java:73)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables.visit(ProcessVariables.java:48)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:25)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:13)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:74)
	at jadx.core.ProcessClass.forceProcess(ProcessClass.java:137)
	at jadx.core.dex.visitors.InlineMethods.processInvokeInsn(InlineMethods.java:66)
	at jadx.core.dex.visitors.InlineMethods.visit(InlineMethods.java:49)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:25)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:13)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:74)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:109)
	at jadx.core.dex.nodes.ClassNode.generateClassCode(ClassNode.java:400)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:388)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:308)
	at jadx.api.JavaClass.load(JavaClass.java:132)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:61)
	at jadx.gui.treemodel.JClass.getCodeInfo(JClass.java:123)
	at jadx.gui.ui.MainWindow.preLoadOpenTabs(MainWindow.java:1608)
	at jadx.gui.ui.MainWindow.lambda$onOpen$5(MainWindow.java:651)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Jadx version

r2360.de62954

### Java version

21.0.5

### OS

- [ ] Windows
- [X] Linux
- [ ] macOS

**Comment by skylot** [comment] 2024-12-25 18:58
Duplicate of #2380.
It is already fixed and works fine for your sample.
Check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Closed by skylot** 2024-12-25 18:58 UTC
Labels: bug, GUI
