### ISSUE TITLE
[core] 

### ISSUE THREAD

**Issue by yangjw** [skylot/jadx#2028] opened 2023-10-09 13:23 UTC
### Issue details

% jadx
Unrecognized VM option 'MaxRAMPercentage=70.0'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by jpstotz** [comment] 2023-10-09 14:17
`Unrecognized VM option 'MaxRAMPercentage=70.0'` is usually an indicator that the used Java Runtime is pretty old. 

Possible duplicate of #1520

**Closed** 2023-10-09 17:47 UTC
Labels: bug, Core
