### ISSUE TITLE
[gui] Smali debugger launch app error.

### ISSUE THREAD

**Issue by ZhanYiBai** [skylot/jadx#2292] opened 2024-10-06 09:59 UTC
### Issue details

When I click Launch app, it tell me , can't find Main Activity Class. Then I close it , and i click button: go to main activity, the same error occurs again. so i used previous version 1.4.7, then it works. 

### Jadx version

1.5.0

### Java version

19.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment] 2024-10-06 11:17
Are you sure the MainActivity class exists in the app? Android apps don't need to have a MainActivity, e.g. apps targeting Android-TV usually have no MainActivity if they are not also targeting Android phones/tablets. Also some hidden apps don't have a MainActivity.

Can you share the APK file that doesn't work?

**Comment by AndreiKud** [comment] 2024-10-12 15:33
@jpstotz here is empty new project, jumps do not work with `WARN : Cannot codeJump because selectedTab is null` in logs.
[app-debug.zip](https://github.com/user-attachments/files/17350588/app-debug.zip)

**Comment by jpstotz** [comment] 2024-10-12 15:56
@AndreiKud Indeed Jadx seems to have a problem when you execute "Go to main Activity" when there is no tab open (no class or resource file opened). Then `codeJump` function refuses to work and outputs the warning `Cannot codeJump because selectedTab is null` (tested in latest unstable version).

Do you remember if this warning was also printed when you click "Launch app"?

@skylot If I remove the `selectedTab == null` check in `jadx.gui.ui.tab.TabsController#codeJump(jadx.gui.utils.JumpPosition)` the function "Go to main Activity" works as expected even if no tab is opened. I checked all implementations of `onTabCodeJump` that receive `selectedTab` as argument but I wasn't able to find an implementation that makes use of it. Thus it seems that we can remove the `selectedTab == null` check.

**Comment by AndreiKud** [comment] 2024-10-12 16:08
@jpstotz just in case you adressed "launch app" to me, the topic starter is @ZhanYiBai

**Comment by skylot** [comment] 2024-10-12 16:36
> If I remove the selectedTab == null check

@jpstotz correct tab events should be: `open`, `select`, `code jump`, so looks like instead of removing check we need to call `select` method (which will call open) and after that produce `code jump` event.
So code jump method should be like this:
```java
	public void codeJump(JumpPosition pos) {
		if (selectedTab == null || selectedTab.getNode() != pos.getNode()) {
			selectTab(pos.getNode());
		}
		listeners.forEach(l -> l.onTabCodeJump(selectedTab, pos));
	}
```
Although, I agree, such event model is confusing, and I see that different methods are called just to "open tab".
This need to be simplified, but I am not sure how to do this yet :disappointed:

**Comment by skylot** [comment] 2024-10-12 18:43
I commit mentioned changes, also I reviewed tab events and can't find a solution to reduce events amount because all of them are used and have their own purpose.
Short tab events description:
- `open` - tab opened without become active (used in tabs restore methods)
- `select` - tab selected by user, also used to change active tab by "quick tabs panel"
- `code jump` - change cursor position in selected tab. Method with same name in `TabsController` provide simple way to do all work of loading and sending all needed events, this method should be used for all code navigation.

**Comment by skylot** [comment] 2024-10-12 18:47
Looks like cause of the original issue is still unknown and author not provide details to help reproduce it, so I will close it.

**Closed by skylot** 2024-10-12 18:47 UTC
Labels: bug, GUI
