### ISSUE TITLE
when search, tips is  Index is not initialized, search will be disabled.

### ISSUE THREAD

**Issue by ElegantDancer** [skylot/jadx#235] opened 2018-03-05 09:58 UTC

**Comment by flynnch** [comment] 2018-03-07 03:18
+1

**Comment by zjinpeng** [comment] 2018-03-12 10:48
+1

**Comment by skylot** [comment] 2018-03-28 07:07
Can anyone write how to reproduce this issue?

**Comment by lifegh** [comment] 2018-03-28 10:14
![default](https://user-images.githubusercontent.com/17618424/38023045-cbfa15b8-32b3-11e8-9c6a-26db12da7dcf.PNG)

**Comment by lifegh** [comment] 2018-03-28 10:15
jadx-0.6.1，search is enabled
jadx-0.7.1，search is disabled

![default](https://user-images.githubusercontent.com/17618424/38023045-cbfa15b8-32b3-11e8-9c6a-26db12da7dcf.PNG)

**Comment by jpstotz** [comment] 2018-03-28 14:42
I am also not able to reproduce this issue. Please post you OS; Java version and your preferences. 
Does it happen with all APKs you load or only specific?

May be the index creation fails on specific APKs?

**Comment by lifegh** [comment] 2018-03-29 02:06
OS:   Windows 10  1709
APK:  All APKs I have

java  9.0.4  +  jadx 0.7.1 ,   reproduce this issue
java  9.0.4  +  jadx 0.6.1 ,   it not happen
java 1.8.0_162  + jadx 0.7.1 ,  it not happen
java 1.8.0_162  + jadx 0.6.1 ,  it not happen

**Comment by skylot** [comment] 2018-03-29 18:31
@lifegh Thank you!
I fixed this issue in [unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files), please confirm that it is gone.

**Comment by lifegh** [comment] 2018-03-30 05:14
@skylot Thanks for fix
yes, it is gone.

but "jadx-gui.bat" can not run on java 10, you should remove "-d64" in the "jadx-gui.bat",  because java 10 not support "-d64"
![vm](https://user-images.githubusercontent.com/17618424/38125247-ba7dbd0e-341a-11e8-8308-2ff619407cb8.png)
![image](https://user-images.githubusercontent.com/17618424/38125451-1c47cb96-341c-11e8-8b41-a57211919540.png)

**Comment by sergey-wowwow** [comment] 2019-03-25 20:56
As the fix is verified
> yes, it is gone.

Closing the report

**Closed by sergey-wowwow** 2019-03-25 20:56 UTC
