### ISSUE TITLE
Exclude does not exclude files from save

### ISSUE THREAD

**Issue by dazzleworth** [skylot/jadx#1087] opened 2021-01-20 09:21 UTC
I'm trying to exclude all other files from decompilation other than app core files eg. com.mycompany.myApp.*. I don't want other packages to be in the decompiled source files. 

For example, I don't want the excluded packages (greyed out) when I click SaveAll. I only want the packages in yellow.

I managed to fix this until you rewrote all your APIs and I lost this functionality recently when I couldn't merge! I'm very disappointed! What is the exclude packages for if I cant selectively save sources?????!!

![image](https://user-images.githubusercontent.com/33960589/105154601-accdbc00-5b44-11eb-9541-ef92b3862bed.png)
@skylot

**Comment by alissonlauffer** [comment] 2021-01-20 09:54
Duplicate of #534.

**Closed** 2021-01-20 10:06 UTC
Labels: Core, bug
