### ISSUE TITLE
[gui] file not found when add jadx-gui.exe to windows PATH

### ISSUE THREAD

**Issue by dannyZhou** [skylot/jadx#2162] opened 2024-04-24 13:00 UTC
### Issue details

Repurduce:

1. download jadx.
2. extract to `c:\sfbin\jadx\`
3. add `c:\sfbin\jadx` to system environment `PATH`
4. open powershell
5. `cd c:\apk`
6. `jadx-gui .\a.apk` show error `Caused by: java.nio.file.NoSuchFileException: .\a.apk`
7. `jadx-gui c:\apk\a.apk` works fine.

### Jadx version

1.5.0

### Java version

21.0.3

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment] 2024-04-24 14:02
That seem to be caused by the launch4j generated `jad-gui.exe`. By default it changes the current directory to the director of the executable. 

https://github.com/TheBoegl/gradle-launch4j ->`String chdir`

I don't think Jadx requires this change of the current directory, thus we could add the launch4j config `chdir.set("")` to disable this behavior.

**Comment by skylot** [comment] 2024-04-24 17:50
Fixed in PR #2160 by @jpstotz.

> By default it changes the current directory to the director of the executable.

I wonder why this was done this way by default :thinking:

**Closed by skylot** 2024-04-24 17:50 UTC
Labels: bug, GUI
