### ISSUE TITLE
[feature]chat

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1021] opened 2020-11-18 09:27 UTC
I just saw a post where the author introduced his own improved version of JADX, and I was wondering what the jADX author thought of it?
https://bbs.pediy.com/thread-263562.htm
https://github.com/pkilller/super-jadx
![image](https://user-images.githubusercontent.com/42903751/99511386-28837f00-29c3-11eb-9cdc-bfe0cd4a20ae.png)

**Comment by jpstotz** [comment] 2020-11-18 10:06
@xmhwws I only have contributed very few changes to Jadx, hence I would not call me an author, but in my opinion this is the way open source works. From what I see this "super-jadx" bases on Jadx 1.0.0 and an renaming feature added. Jadx also has a renaming feature now, which one works better, I don't know. As the "super-jadx" project is not a proper Github fork of jadx it seems like the author is not interested in contributing changes back into Jadx which is a valid decision. As the project name has been changed the probability that somebody mixes up both projects is not very high. 

I also did some time ago create a fork + release of Jadx as an experiment for adding a Jimple/[Soot](https://github.com/soot-oss/soot) based output. But that was just a fun project more or less for personal usage, with no real benefit for most of the Jadx users.

**Comment by xmhwws** [comment] 2020-11-18 10:58
Oh, I'm sorry, there might be a problem with my presentation.
I felt good about some of the features in this enhanced version and wanted to ask the authors of JADX if they would consider integrating them.

The following is from the translation:
![image](https://user-images.githubusercontent.com/42903751/99521419-5b337480-29cf-11eb-9ef6-248d262718b1.png)
What are the shortcomings of the latest JADX 1.2.0?
Today I briefly tried the latest JADX and found the following shortcomings:
1.Renaming variables within a method is not supported.
2.Automatic renaming of override's other methods in parent and subclasses is not supported.(If you rename only 1 method, it will cause a logical error in the code.)
3.The partial Override method is buggy when it is renamed and will not be reflected.
![image](https://user-images.githubusercontent.com/42903751/99521576-8c13a980-29cf-11eb-8793-cb47b13a2e7f.png)
What is super-Jadx?
uper-jadx is my enhanced version based on native JADX and is intended for use by The Android reverse engineer.The following features have been added:
1.Added support for renaming classes, methods, fields, and variables (not supported by native JADx).
2.Rename the override, interface method by association (not supported by native JADx).
3.Duplicate name checks (automatically correlate checks on the override, interface methods of other classes and interfaces).Native JADX is not supported.
![image](https://user-images.githubusercontent.com/42903751/99521666-a9487800-29cf-11eb-89a6-f4c89ba22a57.png)
Why did you do this super-Jadx?
The search function of JADX is very easy to use, but it is a pity that the renaming of UI interface has not been supported. I have been looking forward to the author's support from Skylot, and many people expressed this demand in the Issues of Skylot/JADx. At that time, Skylot made it clear for many times that the renaming function would not be added, and the positioning of JADX was just decomcompiling code.
So I spent a bit of time architecting and reworking JADX late last year and this year, gradually adding renaming features, which was definitely a necessity for my personal work.
So I enhanced JADX prior to Skylot.

**Comment by skylot** [comment] 2020-11-18 12:24
@xmhwws thanks for bringing up this discussion.
It is true, that for me core decompiler functionality always will be the top priority, as soon as this part far from ideal I am spending most of the time improving it. As for other parts like deobfuscation, renaming, resources decoding: those were mostly added and supported by other contributors via PRs. And it is sad that @pkilller decided not to contribute to jadx, but create own project.

About renaming functionality: base implementation was created by @S-trace and I very thankful for this. I just fixed some issues and merged it into master. That was some time ago, and since then I don't see any new issues, so I thought it is ok to made a release. But as you mention, looks like we missed issue with renaming of overridden methods. I am really sorry for this, I will try to find samples to reproduce such issue and fix it.
Also, the renaming of method variables is not implemented in jadx, and I agree that it will be a nice feature. I will add it to tasks backlog.

As a conclusion:
I know many people expect that jadx will evolve into full featured reverse engineering IDE.
But I can't make it alone, even if I work fulltime. So I hope someone can help me to add and **support** new features.
And I really mean **support** because just implement some feature is not enough, there are always errors and issues that needs to be fixed.
Anyway, any contributions are welcome :smiley:

**Comment by Surendrajat** [comment] 2021-01-27 13:07
@skylot I think this can be closed now as all features are implemented in Jadx itself.

**Comment by skylot** [comment] 2021-01-27 13:22
Summary:
- [x] Added support for renaming classes, methods, fields, and variables
- [x] Rename the override, interface method by association
- [ ] Duplicate name checks (automatically correlate checks on the override, interface methods of other classes and interfaces)

@Surendrajat I am still not sure about third issue, if anyone knew how to reproduce it please share (open new issue with reference to this one).
Anyway most of this issue is resolved, so I also think it is OK to close it.

**Closed by skylot** 2021-01-27 13:22 UTC
Labels: new feature
