### ISSUE TITLE
Decompile error on twitch apk

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [skylot/jadx#215] opened 2018-01-25 03:15 UTC
Using version 5.8.3 of the twitch apk in the google play store, many methods are not being decompiled properly throwing a method processing error, usually all stemming from a null pointer exception.  The easiest one to find that I know of is the class file `tv.twitch.android.social.q` which has one of the methods trace below.

```
private final java.lang.CharSequence a(int r1, tv.twitch.chat.ChatMessageBadge[] r2, tv.twitch.android.social.h.a r3, boolean r4) {
        /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.DecodeException: Load method exception: null in method: tv.twitch.android.social.q.a(int, tv.twitch.chat.ChatMessageBadge[], tv.twitch.android.social.h$a, boolean):java.lang.CharSequence
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:116)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:249)
	at jadx.core.ProcessClass.process(ProcessClass.java:31)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:323)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
Caused by: java.lang.NullPointerException
*/
        /*
        r0 = this;
        r1 = 0;
        if (r4 >= 0) goto L_0x000d;
    L_0x0003:
        r0 = -1;
        if (r4 == r0) goto L_0x000d;
    L_0x0006:
        r0 = 1;
    L_0x0007:
        if (r7 != 0) goto L_0x000b;
    L_0x0009:
        if (r0 == 0) goto L_0x000f;
    L_0x000b:
        r0 = 0;
        return r0;
    L_0x000d:
        r0 = r1;
        goto L_0x0007;
    L_0x000f:
        r5 = (java.lang.Object[]) r5;
        r0 = new java.util.ArrayList;
        r0.<init>();
        r0 = (java.util.Collection) r0;
        r2 = r1;
        r1 = r5.length;
        if (r2 >= r1) goto L_0x002d;
    L_0x001c:
        r1 = r5[r2];
        r1 = (tv.twitch.chat.ChatMessageBadge) r1;
        r1 = r3.a(r1, r4, r6);
        if (r1 == 0) goto L_0x0029;
        r0.add(r1);
        r1 = r2 + 1;
        r2 = r1;
        goto L_0x0019;
        r0 = (java.util.List) r0;
        r0 = (java.util.Collection) r0;
        r1 = r0.size();
        r1 = new java.lang.CharSequence[r1];
        r0 = r0.toArray(r1);
        if (r0 != 0) goto L_0x0047;
        r0 = new c.h;
        r1 = "null cannot be cast to non-null type kotlin.Array<T>";
        r0.<init>(r1);
        throw r0;
        r0 = (java.lang.CharSequence[]) r0;
        r1 = r0.length;
        r0 = java.util.Arrays.copyOf(r0, r1);
        r0 = (java.lang.CharSequence[]) r0;
        r0 = android.text.TextUtils.concat(r0);
        goto L_0x000c;
        */
        throw new UnsupportedOperationException("Method not decompiled: tv.twitch.android.social.q.a(int, tv.twitch.chat.ChatMessageBadge[], tv.twitch.android.social.h$a, boolean):java.lang.CharSequence");
    }


```

Quite a few classes are now throwing method decode errors, which pre-version 5.8.X I never had any issues.  Please let me know if there is any more information you need from me.

**Comment by enovella** [comment] 2018-01-25 09:49
Hi @BatedUrGonnaDie,

can you upload the APK in this post? So everyone can reproduce.

Cheers

**Comment by skylot** [comment] 2018-01-25 12:02
I found this APK: [tv.twitch.android.app_5.8.3.apk.zip] (remove `.zip` from filename)(https://github.com/skylot/jadx/files/1663736/tv.twitch.android.app_5.8.3.apk.zip)
Usually for APK download I use [apkpure](https://apkpure.co/twitch-2/), also it allows to download old versions.

This issue caused by `if` which jumps to `nop` instruction and jadx don't expect this.
I have made quick fix and looks like it solve the issue.

**Comment by BatedUrGonnaDie** [comment] 2018-01-25 15:05
Sorry about that @enovella , in the readme it said you could just put the name if it was on the google play store but it makes more sense to just link it directly in the thread so there is no confusion.  The one that @skylot linked is the version that I'm talking about.

I'll pull the branch down @skylot and see if I find anything else that is not decompiling.

**Comment by BatedUrGonnaDie** [comment] 2018-01-25 15:17
Looks like in the same file there is one of the methods is now throwing a new error.
```

    private final java.lang.CharSequence a(tv.twitch.android.social.e r11, tv.twitch.android.social.h.a r12, boolean r13, boolean r14, boolean r15, tv.twitch.android.app.core.WebViewDialogFragment.a r16, tv.twitch.android.util.androidUI.TwitchURLSpan.a r17, java.util.ArrayList<com.bumptech.glide.c.d.e.c> r18) {
        /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: Can't find immediate dominator for block B:46:0x00d7 in {7, 9, 10, 13, 16, 17, 20, 21, 24, 25, 28, 29, 34, 35, 36, 40, 43, 44, 45} preds:[]
	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.computeDominators(BlockProcessor.java:129)
	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:48)
	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:38)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:323)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
*/
        /*
        r10 = this;
        r1 = r11.getTokens();
        if (r1 == 0) goto L_0x00d5;
    L_0x0006:
        r7 = r1;
        r7 = (java.lang.Object[]) r7;
        r1 = new java.util.ArrayList;
        r1.<init>();
        r8 = r1;
        r8 = (java.util.Collection) r8;
        r1 = 0;
        r9 = r1;
    L_0x0014:
        r1 = r7.length;
        if (r9 >= r1) goto L_0x00ab;
    L_0x0017:
        r1 = r7[r9];
        r1 = (tv.twitch.chat.ChatMessageToken) r1;
        r2 = r1.type;
        if (r2 != 0) goto L_0x0029;
    L_0x001f:
        r1 = 0;
    L_0x0020:
        if (r1 == 0) goto L_0x0025;
    L_0x0022:
        r8.add(r1);
    L_0x0025:
        r1 = r9 + 1;
        r9 = r1;
        goto L_0x0014;
    L_0x0029:
        r3 = tv.twitch.android.social.r.a;
        r2 = r2.ordinal();
        r2 = r3[r2];
        switch(r2) {
            case 1: goto L_0x0035;
            case 2: goto L_0x0048;
            case 3: goto L_0x005d;
            case 4: goto L_0x0077;
            case 5: goto L_0x0090;
            default: goto L_0x0034;
        };
    L_0x0034:
        goto L_0x001f;
    L_0x0035:
        if (r1 != 0) goto L_0x003f;
    L_0x0037:
        r1 = new c.h;
        r2 = "null cannot be cast to non-null type tv.twitch.chat.ChatTextToken";
        r1.<init>(r2);
        throw r1;
    L_0x003f:
        r1 = (tv.twitch.chat.ChatTextToken) r1;
        r1 = r10.a(r1);
        r1 = (java.lang.CharSequence) r1;
        goto L_0x0020;
    L_0x0048:
        if (r1 != 0) goto L_0x0052;
    L_0x004a:
        r1 = new c.h;
        r2 = "null cannot be cast to non-null type tv.twitch.chat.ChatEmoticonToken";
        r1.<init>(r2);
        throw r1;
    L_0x0052:
        r1 = (tv.twitch.chat.ChatEmoticonToken) r1;
        r2 = r11.getUserId();
        r1 = r10.a(r1, r12, r13, r2);
        goto L_0x0020;
    L_0x005d:
        if (r1 != 0) goto L_0x0067;
    L_0x005f:
        r1 = new c.h;
        r2 = "null cannot be cast to non-null type tv.twitch.chat.ChatMentionToken";
        r1.<init>(r2);
        throw r1;
    L_0x0067:
        r1 = (tv.twitch.chat.ChatMentionToken) r1;
        r2 = r11.getUserName();
        r3 = "chatMessageInterface.userName";
        c.d.b.i.a(r2, r3);
        r1 = r10.a(r1, r2, r15);
        goto L_0x0020;
    L_0x0077:
        if (r1 != 0) goto L_0x0081;
    L_0x0079:
        r1 = new c.h;
        r2 = "null cannot be cast to non-null type tv.twitch.chat.ChatUrlToken";
        r1.<init>(r2);
        throw r1;
    L_0x0081:
        r2 = r1;
        r2 = (tv.twitch.chat.ChatUrlToken) r2;
        r1 = r10;
        r3 = r12;
        r4 = r16;
        r5 = r17;
        r6 = r14;
        r1 = r1.a(r2, r3, r4, r5, r6);
        goto L_0x0020;
    L_0x0090:
        r2 = r10.c;
        if (r2 == 0) goto L_0x00a8;
    L_0x0094:
        if (r1 != 0) goto L_0x009e;
    L_0x0096:
        r1 = new c.h;
        r2 = "null cannot be cast to non-null type tv.twitch.chat.ChatBitsToken";
        r1.<init>(r2);
        throw r1;
    L_0x009e:
        r1 = (tv.twitch.chat.ChatBitsToken) r1;
        r0 = r18;
        r1 = r10.a(r1, r2, r12, r0);
        goto L_0x0020;
    L_0x00a8:
        r1 = 0;
        goto L_0x0020;
        r8 = (java.util.List) r8;
        r8 = (java.util.Collection) r8;
        r1 = r8.size();
        r1 = new java.lang.CharSequence[r1];
        r1 = r8.toArray(r1);
        if (r1 != 0) goto L_0x00c5;
    L_0x00bd:
        r1 = new c.h;
        r2 = "null cannot be cast to non-null type kotlin.Array<T>";
        r1.<init>(r2);
        throw r1;
    L_0x00c5:
        r1 = (java.lang.CharSequence[]) r1;
        if (r1 == 0) goto L_0x00d5;
    L_0x00c9:
        r2 = r1.length;
        r1 = java.util.Arrays.copyOf(r1, r2);
        r1 = (java.lang.CharSequence[]) r1;
        r1 = android.text.TextUtils.concat(r1);
    L_0x00d4:
        return r1;
    L_0x00d5:
        r1 = 0;
        goto L_0x00d4;
        */
        throw new UnsupportedOperationException("Method not decompiled: tv.twitch.android.social.q.a(tv.twitch.android.social.e, tv.twitch.android.social.h$a, boolean, boolean, boolean, tv.twitch.android.app.core.WebViewDialogFragment$a, tv.twitch.android.util.androidUI.TwitchURLSpan$a, java.util.ArrayList):java.lang.CharSequence");
    }

```

Looks like this error is being thrown in all places that I was getting a null pointer exception from before.  Another file that has this problem is `tv.twitch.androird.b.a` in the nested `b` class.

**Comment by skylot** [comment] 2018-01-25 15:25
Yeah I see that too, and this is the same error which broke tests. So I am trying to fix this.
@BatedUrGonnaDie thank you for your time and interesting sample for bug fixing!

**Comment by BatedUrGonnaDie** [comment] 2018-01-25 17:37
No problem, jadx has been vital for me in making my xposed module so I really appreciate you taking the time to look into this.

**Comment by skylot** [comment] 2018-01-26 15:01
I have made a fix for this particular class. Anyway in whole apk there are still a lot of other errors. If you need to fix some of them please open a new issue.

**Closed by skylot** 2018-01-26 15:01 UTC

**Comment by BatedUrGonnaDie** [comment] 2018-01-27 02:40
Looks like all the classes I need to inspect are decompiling correctly, thank you again for all your work on jadx.
