### ISSUE TITLE
[core] Unknown opcode: 0xa8

### ISSUE THREAD

**Issue by CaledoniaProject** [skylot/jadx#2063] opened 2023-12-18 23:43 UTC
### Issue details

See stack dump, any suggestions? I can provide you the sample file.

### Relevant log output or stacktrace

```java
ERROR - Dependency scan failed in method: org.xml.sax.helpers.SecuritySupport.<clinit>():void, file: xxxx.jar:org/xml/sax/helpers/SecuritySupport.class
jadx.plugins.input.java.utils.JavaClassParseException: Unknown opcode: 0xa8
	at jadx.plugins.input.java.data.code.JavaCodeReader.visitInstructions(JavaCodeReader.java:71)
	at jadx.core.dex.visitors.usage.UsageInfoVisitor.processInstructions(UsageInfoVisitor.java:112)
	at jadx.core.dex.visitors.usage.UsageInfoVisitor.processMethod(UsageInfoVisitor.java:97)
	at jadx.core.dex.visitors.usage.UsageInfoVisitor.processClass(UsageInfoVisitor.java:86)
	at jadx.core.dex.visitors.usage.UsageInfoVisitor.buildUsageData(UsageInfoVisitor.java:71)
	at jadx.core.dex.visitors.usage.UsageInfoVisitor.init(UsageInfoVisitor.java:55)
	at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:333)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:126)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:72)
	at jadx.gui.ui.MainWindow.lambda$loadFiles$0(MainWindow.java:513)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Jadx version

latest github master

**Comment by skylot** [comment] 2023-12-19 16:06
This is a duplicate of #2039.
As a workaround, for now, you can enable `Decompilation -> Use dx/d8 to convert java bytecode` in preferences

**Closed by skylot** 2023-12-19 16:06 UTC
Labels: bug, Core
