### ISSUE TITLE
JADX ERROR: Failed to decode insn: 0x0020: INVOKE_POLYMORPHIC / JADX ERROR: Failed to decode insn: 0x003D: INVOKE_POLYMORPHIC_RANGE

### ISSUE THREAD

**Issue by hide955** [skylot/jadx#1777] opened 2023-02-02 10:06 UTC
/*  JADX ERROR: Failed to decode insn: 0x0020: INVOKE_POLYMORPHIC r2, r6, r3, r4, method: com.example.myapplication26.MainActivity.invoke_polymorphic():void
        jadx.core.utils.exceptions.DecodeException: Unknown instruction: '0x0020: INVOKE_POLYMORPHIC r2, r6, r3, r4'
        	at jadx.core.dex.instructions.InsnDecoder.decode(InsnDecoder.java:494)
        	at jadx.core.dex.instructions.InsnDecoder.lambda$process$0(InsnDecoder.java:50)
        	at jadx.plugins.input.dex.sections.DexCodeReader.visitInstructions(DexCodeReader.java:85)
        	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:45)
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:145)
        	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:410)
        	at jadx.core.ProcessClass.process(ProcessClass.java:67)
        	at jadx.core.ProcessClass.generateCode(ProcessClass.java:115)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:384)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:308)
        */

    /*  JADX ERROR: Failed to decode insn: 0x003D: INVOKE_POLYMORPHIC_RANGE r4, r5, r6, r7, r8, r9, r10, r11, method: com.example.myapplication26.MainActivity.invoke_polymorphic_range():void
        jadx.core.utils.exceptions.DecodeException: Unknown instruction: '0x003D: INVOKE_POLYMORPHIC_RANGE r4, r5, r6, r7, r8, r9, r10, r11'
        	at jadx.core.dex.instructions.InsnDecoder.decode(InsnDecoder.java:494)
        	at jadx.core.dex.instructions.InsnDecoder.lambda$process$0(InsnDecoder.java:50)
        	at jadx.plugins.input.dex.sections.DexCodeReader.visitInstructions(DexCodeReader.java:85)
        	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:45)
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:145)
        	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:410)
        	at jadx.core.ProcessClass.process(ProcessClass.java:67)
        	at jadx.core.ProcessClass.generateCode(ProcessClass.java:115)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:384)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:308)
        */

**Comment by skylot** [comment] 2023-02-02 13:28
@hide955 is it possible to share an app apk or at least a method smali?
This instruction is rare now on Android (after d8), and I am not sure how to get this instruction by compiling from source.

Duplicate of #384

**Comment by hide955** [comment] 2023-02-03 02:31
[app-debug.zip](https://github.com/skylot/jadx/files/10575054/app-debug.zip)

**Comment by skylot** [comment] 2023-02-03 17:13
Done. Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Closed by skylot** 2023-02-03 17:13 UTC
Labels: bug, Core, no-sample, waiting for reply
