### ISSUE TITLE
[core] Code restructure failed

### ISSUE THREAD

**Issue by amspeople** [skylot/jadx#727] opened 2019-07-30 18:14 UTC
**Describe error**
- **Class:** c.m.b.a.f.a.D
- **Method:** public final java.lang.String a(byte[] r6, java.io.File r7)
- provide full java stacktrace:
 ```
   /* JADX WARNING: Code restructure failed: missing block: B:10:0x001c, code lost:
        r3 = r1;
        r1 = null;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:14:0x0021, code lost:
        r3 = th;
     */
    /* JADX WARNING: Code restructure failed: missing block: B:9:0x001b, code lost:
        r1 = move-exception;
     */
    /* JADX WARNING: Removed duplicated region for block: B:22:0x002d  */
    /* Code decompiled incorrectly, please refer to instructions dump. */
```

**APK:**
- https://play.google.com/store/apps/details?id=com.yandex.mobile.drive&hl=ru

**Comment by sergey-wowwow** [comment] 2020-04-29 12:59
A duplicate of https://github.com/skylot/jadx/issues/411

**Closed by sergey-wowwow** 2020-04-29 12:59 UTC
Labels: Core, bug
