### ISSUE TITLE
[core]decompilation error in class ProviderFactory of simplexml

### ISSUE THREAD

**Issue by zxt5105515** [skylot/jadx#1377] opened 2022-02-11 03:55 UTC
decompilation error  in class ProviderFactory  of  simplexml ([simple-xml-2.7.1.jar.zip](https://github.com/skylot/jadx/files/8045844/simple-xml-2.7.1.jar.zip))

decompilation java code

``` java
package org.simpleframework.xml.stream;

/* loaded from: simple-xml-2.7.1.jar:org/simpleframework/xml/stream/ProviderFactory.class */
final class ProviderFactory {
    ProviderFactory() {
    }

    public static Provider getInstance() {
        try {
            return new StreamProvider();
        } catch (Throwable th) {
            return new DocumentProvider();
        }
    }
}
```

decompilation smali code
```
###### Class org.simpleframework.xml.stream.ProviderFactory (org.simpleframework.xml.stream.ProviderFactory)
.version 50  # Java 6
.class final super org/simpleframework/xml/stream/ProviderFactory
.source "ProviderFactory.java"

.method <init>()V
    .max stack 1
    .max locals 1

    .local 0 "this" Lorg/simpleframework/xml/stream/ProviderFactory;
    .line 33
    aload 0
    invokespecial java/lang/Object <init> ()V
    return
.end method

.method public static getInstance()Lorg/simpleframework/xml/stream/Provider;
    .max stack 2
    .max locals 1

  :L0
    .line 48
    new org/simpleframework/xml/stream/StreamProvider
    dup
    invokespecial org/simpleframework/xml/stream/StreamProvider <init> ()V
  :L1
    .catch java/lang/Throwable :L0 .. :L1 goto :L2
    .catch java/lang/Throwable :L0 .. :L1 goto :L3
    areturn
  :L2
    .line 49
    .stack same1 java/lang/Throwable
    astore 0
    .local 0 "e" Ljava/lang/Throwable;
    .line 50
    new org/simpleframework/xml/stream/PullProvider
    dup
    invokespecial org/simpleframework/xml/stream/PullProvider <init> ()V
  :L4
    .catch java/lang/Throwable :L2 .. :L4 goto :L3
    areturn
  :L3
    .line 52
    .end local 0 # "e"
    .stack same1 java/lang/Throwable
    astore 0
    .local 0 "e" Ljava/lang/Throwable;
    .line 53
    new org/simpleframework/xml/stream/DocumentProvider
    dup
    invokespecial org/simpleframework/xml/stream/DocumentProvider <init> ()V
    areturn
.end method

```

as you can see :L2 is not in java code

my jadx :
jadx version: 1.3.2
Java VM: OpenJDK 64-Bit Server VM
Java version: 17.0.2

**Comment by tang350476527** [comment] 2022-02-11 14:55
谢谢您的来信，您的邮件已收到！

**Comment by skylot** [comment] 2022-02-16 20:18
Turns out issue was caused by a weird catch table, i.e. one instruction can have several exception handlers with same type. For more general case: one exception handler can shadow others by wider type. I added a check to fix such cases (by removing shadowed handlers), so this issue is fixed now.

**Closed by skylot** 2022-02-16 20:18 UTC
Labels: bug, Core, try-catch, java-input
