### ISSUE TITLE
jadx error: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]

### ISSUE THREAD

**Issue by lucasduffey** [skylot/jadx#188] opened 2017-09-13 22:22 UTC
```
$ jadx MediaProvider.apk 
15:20:10 INFO  - output directory: MediaProvider
15:20:10 ERROR - jadx error: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
com.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 55, 0]
	at com.android.dex.TableOfContents.readHeader(TableOfContents.java:79) ~[dx-1.10.jar:na]
	at com.android.dex.TableOfContents.readFrom(TableOfContents.java:69) ~[dx-1.10.jar:na]
	at com.android.dex.Dex.loadFrom(Dex.java:156) ~[dx-1.10.jar:na]
	at com.android.dex.Dex.<init>(Dex.java:96) ~[dx-1.10.jar:na]
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:94) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:56) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:34) ~[jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121) ~[jadx-core-0.6.1.jar:na]
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:29) ~[jadx-cli-0.6.1.jar:na]
	at jadx.cli.JadxCLI.main(JadxCLI.java:18) ~[jadx-cli-0.6.1.jar:na]
```

**Comment by jpstotz** [comment] 2017-09-16 19:42
This is duplicate of #144

**Closed** 2017-09-16 23:07 UTC
